### PR TITLE
Rename `GcObject` to `JsObject`

### PR DESCRIPTION
**Pull request by bartlomieju**
Related to #1376

### CODE REVIEW

**Comment by bartlomieju** [comment]
@HalidOdat PTAL and let me know if you want to rename `boa::Result` to `JsResult` as well.

**Review by HalidOdat — APPROVED** [review]

**Review by Razican — APPROVED** [review]
Looks good to me, thanks!

**Comment by Razican** [comment]
This just requires a rebase

**Comment by bartlomieju** [comment]
> This just requires a rebase

This is now done.

**Pull request merged**
