### PR TITLE
fix(boa): 15.4.4.19-8-c-ii-1.js

### LINKED ISSUE #1306: Some Test262 tests run forever
**Describe the bug**
We are ignoring some Test262 tests because they run forever. Here you have the list of them:

 - [`test/built-ins/String/prototype/padStart/fill-string-empty.js`](https://github.com/tc39/test262/blob/e793512b55c199de6abc392d1be4de7325dae544/test/built-ins/String/prototype/padStart/fill-string-empty.js)
 - [`test/built-ins/String/prototype/padEnd/fill-string-empty.js`](https://github.com/tc39/test262/blob/e793512b55c199de6abc392d1be4de7325dae544/test/built-ins/String/prototype/padEnd/fill-string-empty.js)
 - [`test/built-ins/Array/prototype/map/15.4.4.19-8-c-ii-1.js`](https://github.com/tc39/test262/blob/e793512b55c199de6abc392d1be4de7325dae544/test/built-ins/Array/prototype/map/15.4.4.19-8-c-ii-1.js)
 - [`test/built-ins/Array/prototype/unshift/throws-if-integer-limit-exceeded.js`](https://github.com/tc39/test262/blob/e793512b55c199de6abc392d1be4de7325dae544/test/built-ins/Array/prototype/unshift/throws-if-integer-limit-exceeded.js)
 - [`test/built-ins/Array/prototype/concat/arg-length-exceeding-integer-limit.js`](https://github.com/tc39/test262/blob/e793512b55c199de6abc392d1be4de7325dae544/test/built-ins/Array/prototype/concat/arg-length-exceeding-integer-limit.js)
 - [`test/built-ins/Array/prototype/includes/length-boundaries.js`](https://github.com/tc39/test262/blob/e793512b55c199de6abc392d1be4de7325dae544/test/built-ins/Array/prototype/includes/length-boundaries.js)

**To Reproduce**
You can reproduce any of them by running the following command after removing them from the `test_ignore.txt` file:
```bash
cargo run --release --bin boa_tester -- run -s {test_path}
```

**Expected behavior**
These tests should run reasonably fast (usually not more than a second), but they run forever. A fix should make this happen. Some of them might be easier to fix than others.

### PR DESCRIPTION
**Pull request by neeldug**
This Pull Request fixes/closes #1306.

It changes the following:

- skips undefined values on callback

todo: speedup execution of [construct array](https://github.com/boa-dev/boa/blob/cf5ffbf1ad13d3a4cef8b0ce4025fa68859f9306/boa/src/builtins/array/mod.rs#L253-L277), currently stalls for large arrays of mainly undefined values.

### CODE REVIEW

**Comment by neeldug** [comment]
@Razican this will still stall on execution due to the utility function for creating array objects being super slow, not totally familiar with JS array objects and so not too sure if there's a way to avoid iterating through the entire array.

**Comment by Razican** [comment]
### Test262 conformance changes:
  | Test result | master count | PR count | difference |
  | :---------: | :----------: | :------: | :--------: |
  | Total | 78,897 | 78,897 | 0 |
  | Passed | 26,941 | 26,941 | 0 |
  | Ignored | 15,628 | 15,626 | **-2** |
  | Failed | 36,328 | 36,330 | **+2** |
  | Panics | 0 | 0 | 0 |
  | Conformance | 34.15% | 34.15% | 0.00% |
  
  <details><summary><b>Fixed tests:</b></summary>
  
  ```
  test/built-ins/Array/prototype/map/15.4.4.19-8-5.js [strict mode] (previously Failed)
  test/built-ins/Array/prototype/map/15.4.4.19-8-5.js (previously Failed)
  test/built-ins/Array/prototype/map/15.4.4.19-8-b-3.js [strict mode] (previously Failed)
  test/built-ins/Array/prototype/map/15.4.4.19-8-b-3.js (previously Failed)
  test/built-ins/Array/prototype/map/15.4.4.19-8-b-14.js [strict mode] (previously Failed)
  test/built-ins/Array/prototype/map/15.4.4.19-8-b-14.js (previously Failed)
  test/built-ins/Array/prototype/map/15.4.4.19-8-b-9.js [strict mode] (previously Failed)
  test/built-ins/Array/prototype/map/15.4.4.19-8-b-9.js (previously Failed)
  test/built-ins/Array/prototype/map/15.4.4.19-8-9.js [strict mode] (previously Failed)
  test/built-ins/Array/prototype/map/15.4.4.19-8-9.js (previously Failed)
  test/built-ins/Array/prototype/map/15.4.4.19-8-b-10.js [strict mode] (previously Failed)
  test/built-ins/Array/prototype/map/15.4.4.19-8-b-10.js (previously Failed)
  test/built-ins/Array/prototype/map/15.4.4.19-8-b-8.js [strict mode] (previously Failed)
  test/built-ins/Array/prototype/map/15.4.4.19-8-b-8.js (previously Failed)
  test/built-ins/Array/prototype/map/15.4.4.19-8-3.js [strict mode] (previously Failed)
  test/built-ins/Array/prototype/map/15.4.4.19-8-3.js (previously Failed)
  test/built-ins/Array/prototype/map/15.4.4.19-8-c-ii-19.js [strict mode] (previously Failed)
  test/built-ins/Array/prototype/map/15.4.4.19-8-c-ii-19.js (previously Failed)
  test/built-ins/Array/prototype/map/15.4.4.19-8-b-11.js [strict mode] (previously Failed)
  test/built-ins/Array/prototype/map/15.4.4.19-8-b-11.js (previously Failed)
  test/built-ins/Array/prototype/map/15.4.4.19-8-4.js [strict mode] (previously Failed)
  test/built-ins/Array/prototype/map/15.4.4.19-8-4.js (previously Failed)
  ```
  </details>
  
  <details><summary><b>Broken tests:</b></summary>
  
  ```
  test/built-ins/Array/prototype/map/15.4.4.19-4-7.js [strict mode] (previously Passed)
  test/built-ins/Array/prototype/map/15.4.4.19-4-7.js (previously Passed)
  test/built-ins/Array/prototype/map/15.4.4.19-8-c-i-21.js [strict mode] (previously Passed)
  test/built-ins/Array/prototype/map/15.4.4.19-8-c-i-21.js (previously Passed)
  test/built-ins/Array/prototype/map/15.4.4.19-4-5.js [strict mode] (previously Passed)
  test/built-ins/Array/prototype/map/15.4.4.19-4-5.js (previously Passed)
  test/built-ins/Array/prototype/map/15.4.4.19-8-c-i-18.js [strict mode] (previously Passed)
  test/built-ins/Array/prototype/map/15.4.4.19-8-c-i-18.js (previously Passed)
  test/built-ins/Array/prototype/map/15.4.4.19-8-c-i-20.js [strict mode] (previously Passed)
  test/built-ins/Array/prototype/map/15.4.4.19-8-c-i-20.js (previously Passed)
  test/built-ins/Array/prototype/map/15.4.4.19-4-4.js [strict mode] (previously Passed)
  test/built-ins/Array/prototype/map/15.4.4.19-4-4.js (previously Passed)
  test/built-ins/Array/prototype/map/15.4.4.19-8-c-i-22.js [strict mode] (previously Passed)
  test/built-ins/Array/prototype/map/15.4.4.19-8-c-i-22.js (previously Passed)
  test/built-ins/Array/prototype/map/15.4.4.19-4-3.js [strict mode] (previously Passed)
  test/built-ins/Array/prototype/map/15.4.4.19-4-3.js (previously Passed)
  test/built-ins/Array/prototype/map/15.4.4.19-8-c-i-17.js [strict mode] (previously Passed)
  test/built-ins/Array/prototype/map/15.4.4.19-8-c-i-17.js (previously Passed)
  test/built-ins/Array/prototype/map/15.4.4.19-8-c-ii-1.js [strict mode] (previously Ignored)
  test/built-ins/Array/prototype/map/15.4.4.19-8-c-ii-1.js (previously Ignored)
  test/built-ins/Array/prototype/map/15.4.4.19-4-6.js [strict mode] (previously Passed)
  test/built-ins/Array/prototype/map/15.4.4.19-4-6.js (previously Passed)
  test/built-ins/Array/prototype/map/15.4.4.19-8-c-i-19.js [strict mode] (previously Passed)
  test/built-ins/Array/prototype/map/15.4.4.19-8-c-i-19.js (previously Passed)
  ```
  </details>

**Comment by Razican** [comment]
> @Razican this will still stall on execution due to the utility function for creating array objects being super slow, not totally familiar with JS array objects and so not too sure if there's a way to avoid iterating through the entire array.
> 
> The specific call that's taking a huge amount of time, considering the required iterations are 1M can be found [here](https://github.com/boa-dev/boa/blob/cf5ffbf1ad13d3a4cef8b0ce4025fa68859f9306/boa/src/builtins/array/mod.rs#L274).

We can still ignore it until we figure this out. Give a look to the results, though, since many tests seem failing.

**Comment by neeldug** [comment]
@Razican @RageKnify managed to fix the testcase and fix the broken ones in the rewrite, but now some other testcase is stalling, not sure exactly which one if there's a way we could add something to test262 to interrupt execution of a case if it lasts a certain period of time that'd be super useful, and highlight which ones were skipped.

**Comment by neeldug** [comment]
@RageKnify @Razican fixed it for all of map now, should be in line with spec, overall map conformance is 89.55%, which I believe is higher than before.

**Comment by Razican** [comment]
> @RageKnify @Razican fixed it for all of map now, should be in line with spec, overall map conformance is 89.55%, which I believe is higher than before.

Great, thank you! I updated conformance numbers, and it seems there is only one extra broken test. Could you check why?

**Comment by neeldug** [comment]
> Great, thank you! I updated conformance numbers, and it seems there is only one extra broken test. Could you check why?

I'm not totally sure how the realms are supposed to work, really, but I tried running the testcase in node too, and got similar results with some things being undefined, strangely enough when running the code through the interpreter it manages to pass...

**Comment by neeldug** [comment]
@Razican I think above specifies it, it's essentially due to Realms being unimplemented under `array_species_create` as I mentioned before. I believe this functionality wasn't present in the previous version but was rather a false positive, or a seeming pass. I think this PR is ready for merge.

**Review by Razican — APPROVED** [review]

**Review by HalidOdat — APPROVED** [review]
Look good to me! :)

Just needs a rebase

**Review by jasonwilliams — APPROVED** [review]
just needs a rebase

**Pull request merged**
