### PR TITLE
[Merged by Bors] - Correct pop_on_return behaviour

### PR DESCRIPTION
**Pull request by VTCAKAVSMoACE**
This PR changes the following:

- Updates the value of `pop_on_return` after a catch as to prevent VM stack corruption
- Adds two test cases which demonstrate the issue and demonstrate that it has been fixed

I am unsure if it is possible to abuse the patch provided; one would need to catch from within an array initialisation without calling into another frame (e.g., with a lambda), which I don't think is possible.

### CODE REVIEW

**Review by RageKnify — CHANGES_REQUESTED** [review]
Feels weird to not check anything after executing the JS code. We could at least check whether an exception was thrown, in the first case the result of `exec` should be `Err` and in the second case `Ok`, right? Just asserting that they got the right variants feels better than doing nothing else.

**Comment by VTCAKAVSMoACE** [comment]
Sorry for the late response on this; busy Monday. :) Do the changes provided suffice?

**Review by jedel1043 — APPROVED** [review]
Looks good!

**Review by RageKnify — APPROVED** [review]
bors r+

**Pull request closed without merging**
