### PR TITLE
chore: add .devcontainer

### PR DESCRIPTION
**Pull request by LeoDog896**
This adds a rust [dev container](https://containers.dev/) for spinning up a dev environment locally.

### CODE REVIEW

**Comment by raskad** [comment]
I'm not really sure how much of local development files should be in the repo, especially if none of the maintainers use the methods. For example I personally do not use Development Containers. Any other opinions or does anyone use it?

@Razican @jasonwilliams @HalidOdat @RageKnify @jedel1043 @nekevss

**Comment by jasonwilliams** [comment]
I agree with @raskad we used to have a devcontainer in this repo before back in its early days but it wasn’t maintained. 

I think most contributors just use WSL or their own Linux system. Any reason why needing the container?

**Comment by LeoDog896** [comment]
Honestly, I just find it easier to use to spin up a local environment without having to change any of my local computer tooling. However, given that it doesn't have much of a use since the environment setup isn't too complex, I don't see much of a use for it either. If the build process (though I doubt it) ever requires any additional tooling, however, please do let me know.

**Comment by jasonwilliams** [comment]
Boa has remained pretty simple to set up. We assume anyone wanting to contribute to Boa already has some interest in Rust and thus already has the Rust toolchain installed. There isn’t much else needed.

**Pull request closed without merging**
