### PR TITLE
Allow `arguments` and `eval` in the return position of strict functions

### LINKED ISSUE #1598: `arguments` and `eval` should be allowed in the return position in strict functions
In strict mode `arguments` and `eval` are mostly treated as keywords. For example they cannot be assigned to. But they should be allowed as return values from a strict function.

The following code examples currently fail, but should work:

```javascript
let eval = 1;

function a(){
    "use strict";
    return eval;
}

a() // returns 1
```

```javascript
function a(){
    "use strict";
    return arguments;
}

a(1,2) // returns [Arguments] { '0': 1, '1': 2 }
```

Based on the error message a good starting point would be here: https://github.com/boa-dev/boa/blob/c977b8e5aa9634ff0e804daef7510feca69a3d10/boa/src/syntax/lexer/identifier.rs#L119

### PR DESCRIPTION
**Pull request by am-a-man**
This Pull Request fixes/closes #1598 .

It changes the following:

- updated `STRICT_FORBIDDEN_IDENTIFIERS`
- updated `LexicalBinding` to throw Error when assigning to `eval` or `arguments` in strict mode
- updated `VariableDeclaration` to throw Error when assigning to `eval` or `arguments` in strict mode

### CODE REVIEW

**Comment by Razican** [comment]
#### VM implementation
| Test result | main count | PR count | difference |
| :---------: | :----------: | :------: | :--------: |
| Total | 87,912 | 87,912 | 0 |
| Passed | 40,892 | 40,851 | **-41** |
| Ignored | 19,929 | 19,929 | 0 |
| Failed | 27,091 | 27,132 | **+41** |
| Panics | 0 | 0 | 0 |
| Conformance | 46.51% | 46.47% | **-0.05%** |

<details><summary><b>Fixed tests (26):</b></summary>

```
test/language/statements/for-of/arguments-unmapped.js (previously Failed)
test/language/statements/for-of/arguments-unmapped-aliasing.js (previously Failed)
test/language/statements/for-of/arguments-unmapped-mutation.js (previously Failed)
test/language/arguments-object/mapped/nonconfigurable-descriptors-define-failure.js (previously Failed)
test/built-ins/Array/prototype/concat/Array.prototype.concat_strict-arguments.js [strict mode] (previously Failed)
test/built-ins/Array/prototype/concat/Array.prototype.concat_strict-arguments.js (previously Failed)
test/built-ins/ArrayIteratorPrototype/next/args-unmapped-expansion-after-exhaustion.js (previously Failed)
test/built-ins/ArrayIteratorPrototype/next/args-unmapped-expansion-before-exhaustion.js (previously Failed)
test/built-ins/ArrayIteratorPrototype/next/args-unmapped-iteration.js (previously Failed)
test/built-ins/ArrayIteratorPrototype/next/args-unmapped-truncation-before-exhaustion.js (previously Failed)
test/built-ins/ThrowTypeError/unique-per-realm-unmapped-args.js [strict mode] (previously Failed)
test/built-ins/ThrowTypeError/unique-per-realm-unmapped-args.js (previously Failed)
test/built-ins/ThrowTypeError/unique-per-realm-non-simple.js [strict mode] (previously Failed)
test/built-ins/ThrowTypeError/unique-per-realm-non-simple.js (previously Failed)
test/built-ins/ThrowTypeError/forbidden-arguments.js [strict mode] (previously Failed)
test/built-ins/ThrowTypeError/forbidden-arguments.js (previously Failed)
test/built-ins/ThrowTypeError/throws-type-error.js [strict mode] (previously Failed)
test/built-ins/ThrowTypeError/throws-type-error.js (previously Failed)
test/built-ins/ThrowTypeError/is-function.js [strict mode] (previously Failed)
test/built-ins/ThrowTypeError/is-function.js (previously Failed)
test/built-ins/ThrowTypeError/forbidden-caller.js [strict mode] (previously Failed)
test/built-ins/ThrowTypeError/forbidden-caller.js (previously Failed)
test/built-ins/ThrowTypeError/length.js [strict mode] (previously Failed)
test/built-ins/ThrowTypeError/length.js (previously Failed)
test/built-ins/ThrowTypeError/prototype.js [strict mode] (previously Failed)
test/built-ins/ThrowTypeError/prototype.js (previously Failed)
```

</details>

<details><summary><b>Broken tests (67):</b></summary>

```
test/language/expressions/assignmenttargettype/parenthesized-identifierreference-arguments-strict.js [strict mode] (previously Passed)
test/language/expressions/assignmenttargettype/parenthesized-identifierreference-eval-strict.js [strict mode] (previously Passed)
test/language/expressions/assignmenttargettype/direct-identifierreference-eval-strict.js [strict mode] (previously Passed)
test/language/expressions/assignmenttargettype/direct-identifierreference-arguments-strict.js [strict mode] (previously Passed)
test/language/expressions/object/setter-param-eval-strict-outside.js [strict mode] (previously Passed)
test/language/expressions/object/11.1.5-1gs.js [strict mode] (previously Passed)
test/language/expressions/object/setter-param-arguments-strict-outside.js [strict mode] (previously Passed)
test/language/expressions/object/method-definition/early-errors-object-method-arguments-in-formal-parameters.js [strict mode] (previously Passed)
test/language/expressions/object/method-definition/early-errors-object-method-eval-in-formal-parameters.js [strict mode] (previously Passed)
test/language/expressions/logical-assignment/lgcl-or-eval-strict.js [strict mode] (previously Passed)
test/language/expressions/logical-assignment/lgcl-and-arguments-strict.js [strict mode] (previously Passed)
test/language/expressions/logical-assignment/lgcl-and-eval-strict.js [strict mode] (previously Passed)
test/language/expressions/logical-assignment/lgcl-nullish-eval-strict.js [strict mode] (previously Passed)
test/language/expressions/logical-assignment/lgcl-or-arguments-strict.js [strict mode] (previously Passed)
test/language/expressions/logical-assignment/lgcl-nullish-arguments-strict.js [strict mode] (previously Passed)
test/language/expressions/compound-assignment/mult-eval-strict.js [strict mode] (previously Passed)
test/language/expressions/compound-assignment/or-arguments-strict.js [strict mode] (previously Passed)
test/language/expressions/compound-assignment/and-arguments-strict.js [strict mode] (previously Passed)
test/language/expressions/compound-assignment/mod-arguments-strict.js [strict mode] (previously Passed)
test/language/expressions/compound-assignment/sub-arguments-strict.js [strict mode] (previously Passed)
test/language/expressions/compound-assignment/xor-eval-strict.js [strict mode] (previously Passed)
test/language/expressions/compound-assignment/11.13.2-6-1gs.js [strict mode] (previously Passed)
test/language/expressions/compound-assignment/add-arguments-strict.js [strict mode] (previously Passed)
test/language/expressions/compound-assignment/lshift-arguments-strict.js [strict mode] (previously Passed)
test/language/expressions/compound-assignment/mult-arguments-strict.js [strict mode] (previously Passed)
test/language/expressions/compound-assignment/or-eval-strict.js [strict mode] (previously Passed)
test/language/expressions/compound-assignment/urshift-arguments-strict.js [strict mode] (previously Passed)
test/language/expressions/compound-assignment/srshift-arguments-strict.js [strict mode] (previously Passed)
test/language/expressions/compound-assignment/add-eval-strict.js [strict mode] (previously Passed)
test/language/expressions/compound-assignment/sub-eval-strict.js [strict mode] (previously Passed)
test/language/expressions/compound-assignment/and-eval-strict.js [strict mode] (previously Passed)
test/language/expressions/compound-assignment/xor-arguments-strict.js [strict mode] (previously Passed)
test/language/expressions/compound-assignment/lshift-eval-strict.js [strict mode] (previously Passed)
test/language/expressions/compound-assignment/div-arguments-strict.js [strict mode] (previously Passed)
test/language/expressions/compound-assignment/srshift-eval-strict.js [strict mode] (previously Passed)
test/language/expressions/compound-assignment/div-eval-strict.js [strict mode] (previously Passed)
test/language/expressions/compound-assignment/mod-eval-strict.js [strict mode] (previously Passed)
test/language/expressions/compound-assignment/urshift-eval-strict.js [strict mode] (previously Passed)
test/language/expressions/async-generator/early-errors-expression-eval-in-formal-parameters.js [strict mode] (previously Passed)
test/language/expressions/async-generator/early-errors-expression-arguments-in-formal-parameters.js [strict mode] (previously Passed)
test/language/expressions/async-function/early-errors-expression-eval-in-formal-parameters.js [strict mode] (previously Passed)
test/language/expressions/assignment/id-arguments-strict.js [strict mode] (previously Passed)
test/language/expressions/assignment/id-eval-strict.js [strict mode] (previously Passed)
test/language/expressions/assignment/dstr/obj-id-simple-strict.js [strict mode] (previously Passed)
test/language/expressions/arrow-function/syntax/early-errors/arrowparameters-cover-no-eval.js [strict mode] (previously Passed)
test/language/expressions/arrow-function/syntax/early-errors/arrowparameters-bindingidentifier-no-arguments.js [strict mode] (previously Passed)
test/language/expressions/arrow-function/syntax/early-errors/arrowparameters-cover-no-arguments.js [strict mode] (previously Passed)
test/language/expressions/arrow-function/syntax/early-errors/arrowparameters-bindingidentifier-no-eval.js [strict mode] (previously Passed)
test/language/expressions/prefix-decrement/arguments.js [strict mode] (previously Passed)
test/language/expressions/prefix-decrement/11.4.5-2-2gs.js [strict mode] (previously Passed)
test/language/expressions/prefix-decrement/eval.js [strict mode] (previously Passed)
test/language/expressions/prefix-increment/arguments.js [strict mode] (previously Passed)
test/language/expressions/prefix-increment/eval.js [strict mode] (previously Passed)
test/language/directive-prologue/14.1-4gs.js [strict mode] (previously Passed)
test/language/directive-prologue/14.1-4gs.js (previously Passed)
test/language/directive-prologue/14.1-5gs.js [strict mode] (previously Passed)
test/language/statements/async-function/early-errors-declaration-arguments-in-formal-parameters.js [strict mode] (previously Passed)
test/language/statements/async-function/early-errors-declaration-eval-in-formal-parameters.js [strict mode] (previously Passed)
test/language/statements/function/param-eval-strict.js [strict mode] (previously Passed)
test/language/statements/function/13.1-1gs.js [strict mode] (previously Passed)
test/language/statements/function/enable-strict-via-body.js (previously Passed)
test/language/statements/function/13.1-4gs.js [strict mode] (previously Passed)
test/language/statements/function/13.0_4-5gs.js [strict mode] (previously Passed)
test/language/statements/function/param-arguments-strict.js [strict mode] (previously Passed)
test/language/statements/try/catch-parameter-boundnames-restriction-arguments-negative-early.js [strict mode] (previously Passed)
test/language/statements/try/catch-parameter-boundnames-restriction-eval-negative-early.js [strict mode] (previously Passed)
test/language/arguments-object/10.5-1gs.js [strict mode] (previously Passed)
```

</details>

**Review by Razican — COMMENTED** [review]
It's looking pretty good to me, but somehow it's failing a bunch of tests :/

**Comment by Razican** [comment]
@am-a-man could you check if those failing tests can be fixed? Also, this would need a re-base.

**Comment by lupd** [comment]
I took at a look at the failing tests. They are failing because they are no longer returning a SyntaxError.

@am-a-man Are you planning on fixing the regressions?

**Comment by am-a-man** [comment]
@lupd I'll look into it, although it could take some time, sorry for the delay but it could still take some time due to university exams going on. I'll look into it as soon as I get some time.

**Comment by raskad** [comment]
Fixed by #2069

**Pull request closed without merging**
