### PR TITLE
Started with the new lexer implementation

### LINKED ISSUE #294: The lexer doesn't take into account goal symbols
Getting the code from the `harness/assert.js` file in the test262 suite, this fails to parse:
```javascript
function assert(mustBeTrue, message) {
  if (mustBeTrue === true) {
    return;
  }

  if (message === undefined) {
    message = 'Expected true but got ' + assert._toString(mustBeTrue);
  }
  $ERROR(message);
}

assert._isSameValue = function (a, b) {
  if (a === b) {
    // Handle +/-0 vs. -/+0
    return a !== 0 || 1 / a === 1 / b;
  }

  // Handle NaN vs. NaN
  return a !== a && b !== b;
};
```

With the error:
```
ParsingError: Expected one of ';', '}' or 'line terminator', got 'b' at line 24, col 24
```

Interestingly, the error is given in column 24 (marked here):
```
    return a !== 0 || 1 / a === 1 / b;
                       ^
```

But I'm guessing the issue is with the last `b`. I think this is a regression, since this particular file parsed fine before the rewrite, but it might have been something new in the file. Once fixed, we need to add a test for it.

### PR DESCRIPTION
**Pull request by Razican**
This Pull Request fixes #294.

It changes the following:
 - The lexer now can be created with anything that implements `Read`. Ideally, we should use either a `Cursor<String>` if we are reading input from user (for the console, for example), or a buffered reader when reading from files.
 - Adds stream lexing, which can be used with code streams that are not yet completely available.
 - Adds stream parsing. This means that the parser does not need to wait for all the tokens to be lexed before the parsing starts.
 - Adds goal symbols, which means we can correcly identify the difference between a division `/` and a regular expression literal starting with `/`.

Note that this is still WIP. I have only laid out the initials with the new cursor for the lexer, but I wanted to have it here in order to have benchmarks soon, and to receive feedback.

### CODE REVIEW

**Comment by Lan2u** [comment]
Have been looking through this / how the lexer used to work and I think I have a basic understanding of where stuff is. Is there an area within the new lexer that I could look into working on?

**Comment by Razican** [comment]
> Have been looking through this / how the lexer used to work and I think I have a basic understanding of where stuff is. Is there an area within the new lexer that I could look into working on? 

Basically, porting the old lexer to the new architecture would be nice. You can create PRs to this branch. If you find you need something new from the cursor, let me know, and I can add it.

I might have some time this week to finish the unimplemented functions in the cursor. Then we need to have some extra logic to use the goal symbols.

**Comment by Lan2u** [comment]
I see the cursor gets ASCII bytes - what about if unicode is used?

**Comment by Razican** [comment]
> This obviously might come with some performance hit so there might be a better way - macros? - Ideally something like a c:
>  `#define STRING_LITERAL_CHECKS '"' | '\'' `
I see that you created some macros in the PR. I think that's the way to go for now. We'll see if in the future this gets a bit too difficult to maintain or can be improved.


> I see the cursor gets ASCII bytes - what about if unicode is used?

The cursor goes through bytes, independently if they are ASCII or not. Then, there is a wrapper that converts them to Unicode if needed.

**Comment by Lan2u** [comment]
@Razican is it possible to allow putting tokens back onto the cursor? It would be useful for handling cases like regex (or alternatively give the option to peek more than a single cursor ahead).

**Comment by Razican** [comment]
> @Razican is it possible to allow putting tokens back onto the cursor? It would be useful for handling cases like regex (or alternatively give the option to peek more than a single cursor ahead).

Yep, we should be able peek at most 4 characters. Maybe during the weekend I have time to implement that in the cursor.

**Comment by jasonwilliams** [comment]
Is this PR superseeded by #486 ?

**Comment by Lan2u** [comment]
> Is this PR superseeded by #486 ?

I think so unless @Razican has local changes?

**Comment by Razican** [comment]
I have no further local changes, we can close this :)

**Pull request closed without merging**
