### PR TITLE
test(boa): add more coverage

### PR DESCRIPTION
**Pull request by neeldug**
It changes the following:

- improves coverage
- improves conformance for array_buffer
- tidies typos

### CODE REVIEW

**Comment by Razican** [comment]
Hi @neeldug it seems that the last tests are failing. Could you check those so that we can see if we can get this merged?

**Comment by neeldug** [comment]
> Hi @neeldug it seems that the last tests are failing. Could you check those so that we can see if we can get this merged?

Hi, yes — sorry, I started on this a while back but I’ll take a look but from what I could see it was mishandling mutable state in the failing testcase, I’ll take a longer look at it and loop back if needed.

**Comment by neeldug** [comment]
> Hi, yes — sorry, I started on this a while back but I’ll take a look but from what I could see it was mishandling mutable state in the failing testcase, I’ll take a longer look at it and loop back if needed.

Hi @Razican, I'm having a little difficulty in understanding exactly where the testcase is failing, given that currently it seems that the array in the callback function isn't being passed mutably whereas in Node, it behaves such that the array is mutable, whereas the element is not in the callback function. I'm not sure where to go about dealing with this in Boa.

**Comment by Razican** [comment]
> > Hi, yes — sorry, I started on this a while back but I’ll take a look but from what I could see it was mishandling mutable state in the failing testcase, I’ll take a longer look at it and loop back if needed.
> 
> Hi @Razican, I'm having a little difficulty in understanding exactly where the testcase is failing, given that currently it seems that the array in the callback function isn't being passed mutably whereas in Node, it behaves such that the array is mutable, whereas the element is not in the callback function. I'm not sure where to go about dealing with this in Boa.

Hmmm seems something related with interior mutability. In any case, I guess we could just rebase this, ignore that test and merge it. It already improves coverage, which we really need.

**Pull request closed without merging**
