### PR TITLE
[Merged by Bors] - Fix `String.prototype.replace()` order of `ToString` execution

### PR DESCRIPTION
**Pull request by HalidOdat**
Fix order of `ToString` execution, there are 3 failing tests on `.replace()` but they seem to be regex related

### CODE REVIEW

**Review by raskad — APPROVED** [review]
Nice fix and also nice optimization with the enum.

**Review by jedel1043 — APPROVED** [review]
Good work!

**Review by Razican — APPROVED** [review]
Thanks!

**Pull request closed without merging**
