### PR TITLE
Ignore tests from codecov count and disable annotations

### PR DESCRIPTION
**Pull request by HalidOdat**
It changes the following:
 - Disable codecov annotations in PR
 - Ignore tests when calculating coverage

### CODE REVIEW

**Comment by Lan2u** [comment]
For my understanding - which tests aren't being included in coverage?

**Comment by jasonwilliams** [comment]
I'm a bit confused by this, why is codecov including tests as code coverage by default?

**Comment by HalidOdat** [comment]
> For my understanding - which tests aren't being included in coverage?

Pretty much every test

`--ignore-tests 'Ignore lines of test functions when collecting coverage'` 

> I'm a bit confused by this, why is codecov including tests as code coverage by default?

This is what the owner of the repo says: <https://github.com/xd009642/tarpaulin/issues/351#issuecomment-597752231>

**Review by jasonwilliams — APPROVED** [review]
Approve, I also find the annotations distracting

**Review by RageKnify — APPROVED** [review]

**Pull request merged**
