### PR TITLE
Fix evaluation order in destructive property assignments

### PR DESCRIPTION
**Pull request by raskad**
This PR changes the following:

- Fix evaluation order in destructive property assignments

### CODE REVIEW

**Comment by raskad** [comment]
The test diff is still wrong. The only relevant test passing now is `test/language/statements/class/elements/privatefieldset-evaluation-order-1.js (previously Failed)`.

**Comment by jedel1043** [comment]
> The test diff is still wrong. The only relevant test passing now is `test/language/statements/class/elements/privatefieldset-evaluation-order-1.js (previously Failed)`.

Yep, the data repo just didn't update on time. It'll be updated later today

**Review by jedel1043 — APPROVED** [review]
LGTM!

**Review by nekevss — APPROVED** [review]
LGTM

**Pull request merged**
