### PR TITLE
Implement `regress` fixes #478

### LINKED ISSUE #478: Use ECMAScript syntax for regular expressions
**Current situation**
Currently, we use regular expressions from the `regex` crate. They are extremely fast, but they don't support the full ECMAScript syntax like backreferences or lookaround assertions.

**Solution**
We should use a library that does support all this syntax. A nice library that was just released and seems to support this is [`regress`](https://crates.io/crates/regress).

We should remove our dependency on `regex` and use `regress`, and see how the performance gets affected.

### PR DESCRIPTION
**Pull request by neeldug**
This Pull Request fixes/closes #478.

It changes the following:

- refactors methods using regex's find to use regress's find and matching API
- _refactors capture methods using regress's capture group system_ <- TODO

### CODE REVIEW

**Comment by neeldug** [comment]
@Razican was wondering whether you had any idea on how to refactor the capture groups that are failing here.

**Comment by RageKnify** [comment]
I've managed to make it compile, but the tests are failing, I think the creation of the Regex struct needs to change.
I'll get back to this in a few hours.

My work is here: https://github.com/RageKnify/boa/tree/regress

**Comment by Razican** [comment]
> @Razican was wondering whether you had any idea on how to refactor the capture groups that are failing here. Specifically in `boa/src/builtins/regexp/mod.rs`

I would need to give it a look, but I don't think I will have the time this week :/

**Comment by RageKnify** [comment]
@neeldug I believe my branch will finish the PR, it passes `cargo test`.
Would you like it if I opened a PR to your branch or can you rebase it yourself?

**Comment by neeldug** [comment]
I don’t mind @RageKnify, I’ll rebase it myself since that should be easier.

**Comment by RageKnify** [comment]
Sorry to bother @neeldug, but I improved `regress`'s API and simplified `boa`'s code a bit: 812fcee025b1328a7af03371f486b4aec241e590 when you can rebase it please.
I'm not sure how to improve the coverage, RegExp is decently covered.

**Comment by neeldug** [comment]
Ran a rebase for benchmarking to run `crit-cmp` to see if regress's performance is similar to regex.

**Comment by HalidOdat** [comment]
```
┌─────────┬──────────────────────────────────────────────┬──────────────────────┬──────────────────────┬────────────┐
│ (index) │                     name                     │   changesDuration    │    masterDuration    │ difference │
├─────────┼──────────────────────────────────────────────┼──────────────────────┼──────────────────────┼────────────┤
│    0    │     'Arithmetic operations (Execution)'      │   '379.9±17.17ns'    │   '381.6±22.38ns'    │   '0.0'    │
│    1    │        'Arithmetic operations (Full)'        │ '**261.7±14.85µs**'  │   '284.1±23.77µs'    │   '-8.3'   │
│    2    │          'Array access (Execution)'          │     '8.9±0.49µs'     │   '**8.8±0.66µs**'   │   '+1.0'   │
│    3    │            'Array access (Full)'             │ '**292.2±12.89µs**'  │   '309.6±24.35µs'    │   '-5.7'   │
│    4    │         'Array creation (Execution)'         │     '3.3±0.14ms'     │   '**3.2±0.10ms**'   │   '+3.0'   │
│    5    │           'Array creation (Full)'            │   '**3.5±0.11ms**'   │     '3.6±0.17ms'     │   '-2.9'   │
│    6    │           'Array pop (Execution)'            │  '1184.7±115.85µs'   │ '**1131.9±60.09µs**' │   '+5.0'   │
│    7    │              'Array pop (Full)'              │ '**1585.7±47.42µs**' │  '1680.9±111.45µs'   │   '-5.7'   │
│    8    │     'Boolean Object Access (Execution)'      │   '**4.9±0.24µs**'   │     '5.2±0.28µs'     │   '-3.8'   │
│    9    │        'Boolean Object Access (Full)'        │ '**275.6±10.44µs**'  │   '287.3±15.17µs'    │   '-3.8'   │
│   10    │            'Clean js (Execution)'            │ '**762.0±36.29µs**'  │   '864.6±171.29µs'   │   '-12'    │
│   11    │              'Clean js (Full)'               │ '**1075.3±98.32µs**' │   '1087.7±57.34µs'   │  '-0.99'   │
│   12    │             'Clean js (Parser)'              │  '**39.0±1.75µs**'   │    '39.3±2.58µs'     │  '-0.99'   │
│   13    │                'Create Realm'                │ '**481.9±20.59ns**'  │   '485.7±21.76ns'    │  '-0.99'   │
│   14    │ 'Dynamic Object Property Access (Execution)' │     '5.9±0.34µs'     │   '**5.6±0.30µs**'   │   '+5.0'   │
│   15    │   'Dynamic Object Property Access (Full)'    │ '**282.3±12.93µs**'  │   '291.0±10.76µs'    │   '-2.9'   │
│   16    │            'Expression (Parser)'             │     '7.1±0.62µs'     │   '**6.9±0.28µs**'   │   '+4.0'   │
│   17    │           'Fibonacci (Execution)'            │   '930.1±44.44µs'    │ '**903.8±34.10µs**'  │   '+3.0'   │
│   18    │              'Fibonacci (Full)'              │ '**1211.8±78.61µs**' │   '1246.9±93.71µs'   │   '-2.9'   │
│   19    │            'For loop (Execution)'            │    '24.3±1.62µs'     │  '**23.8±1.54µs**'   │   '+2.0'   │
│   20    │              'For loop (Full)'               │ '**306.2±14.02µs**'  │   '318.1±22.39µs'    │   '-3.8'   │
│   21    │             'For loop (Parser)'              │    '19.1±0.82µs'     │  '**19.0±1.69µs**'   │   '+1.0'   │
│   22    │           'Goal Symbols (Parser)'            │  '**13.1±2.02µs**'   │    '13.3±1.98µs'     │   '-2.0'   │
│   23    │            'Hello World (Parser)'            │   '**3.2±0.17µs**'   │     '3.3±0.28µs'     │   '-2.0'   │
│   24    │             'Long file (Parser)'             │ '**815.8±35.56ns**'  │   '823.7±53.28ns'    │  '-0.99'   │
│   25    │            'Mini js (Execution)'             │ '**675.9±36.13µs**'  │   '735.7±94.76µs'    │   '-8.3'   │
│   26    │               'Mini js (Full)'               │ '**967.5±31.01µs**'  │   '1008.6±41.26µs'   │   '-3.8'   │
│   27    │              'Mini js (Parser)'              │    '36.2±4.54µs'     │  '**34.0±1.40µs**'   │   '+7.0'   │
│   28    │      'Number Object Access (Execution)'      │   '**4.0±0.19µs**'   │     '4.0±0.18µs'     │   '-2.0'   │
│   29    │        'Number Object Access (Full)'         │ '**275.2±31.94µs**'  │   '289.0±12.53µs'    │   '-4.8'   │
│   30    │        'Object Creation (Execution)'         │     '5.1±0.46µs'     │   '**5.0±0.35µs**'   │   '+2.0'   │
│   31    │           'Object Creation (Full)'           │ '**278.7±18.04µs**'  │   '295.4±20.03µs'    │   '-5.7'   │
│   32    │             'RegExp (Execution)'             │   '**9.9±0.39µs**'   │    '72.0±6.78µs'     │   '-86'    │
│   33    │               'RegExp (Full)'                │ '**289.1±15.70µs**'  │   '377.4±20.02µs'    │   '-24'    │
│   34    │         'RegExp Literal (Execution)'         │  '**11.2±0.58µs**'   │    '80.4±7.74µs'     │   '-86'    │
│   35    │           'RegExp Literal (Full)'            │  '**287.6±8.34µs**'  │   '382.9±22.88µs'    │   '-25'    │
│   36    │    'RegExp Literal Creation (Execution)'     │   '**9.7±0.43µs**'   │    '80.6±15.17µs'    │   '-88'    │
│   37    │       'RegExp Literal Creation (Full)'       │ '**284.7±14.13µs**'  │   '368.7±13.98µs'    │   '-22'    │
│   38    │ 'Static Object Property Access (Execution)'  │     '5.4±0.33µs'     │   '**5.2±0.22µs**'   │   '+4.0'   │
│   39    │    'Static Object Property Access (Full)'    │ '**281.9±19.55µs**'  │   '291.0±14.14µs'    │   '-2.9'   │
│   40    │      'String Object Access (Execution)'      │   '**7.4±0.35µs**'   │     '7.4±0.56µs'     │  '-0.99'   │
│   41    │        'String Object Access (Full)'         │ '**281.6±10.04µs**'  │   '292.8±14.04µs'    │   '-3.8'   │
│   42    │       'String comparison (Execution)'        │   '**6.5±0.20µs**'   │     '6.9±0.39µs'     │   '-6.5'   │
│   43    │          'String comparison (Full)'          │  '**277.7±7.29µs**'  │   '293.4±12.99µs'    │   '-5.7'   │
│   44    │      'String concatenation (Execution)'      │   '**5.4±0.67µs**'   │     '5.5±0.36µs'     │   '-2.0'   │
│   45    │        'String concatenation (Full)'         │  '**273.1±6.76µs**'  │   '292.2±24.97µs'    │   '-6.5'   │
│   46    │          'String copy (Execution)'           │     '4.2±0.16µs'     │     '4.2±0.41µs'     │   '0.0'    │
│   47    │             'String copy (Full)'             │ '**269.0±12.84µs**'  │   '285.7±11.76µs'    │   '-5.7'   │
│   48    │            'Symbols (Execution)'             │     '3.5±0.22µs'     │   '**3.4±0.29µs**'   │   '+2.0'   │
│   49    │               'Symbols (Full)'               │ '**250.1±10.33µs**'  │   '276.1±27.77µs'    │   '-9.1'   │
│   50    │                      ''                      │      undefined       │      undefined       │   '+NaN'   │
└─────────┴──────────────────────────────────────────────┴──────────────────────┴──────────────────────┴────────────┘
```

Here are the benchmarks you can access this by looking at the benchmark CI log, There seems to be a really big boost in RegExp performance!

```
│   32    │             'RegExp (Execution)'             │   '**9.9±0.39µs**'   │    '72.0±6.78µs'     │   '-86'    │
│   33    │               'RegExp (Full)'                │ '**289.1±15.70µs**'  │   '377.4±20.02µs'    │   '-24'    │
│   34    │         'RegExp Literal (Execution)'         │  '**11.2±0.58µs**'   │    '80.4±7.74µs'     │   '-86'    │
│   35    │           'RegExp Literal (Full)'            │  '**287.6±8.34µs**'  │   '382.9±22.88µs'    │   '-25'    │
│   36    │    'RegExp Literal Creation (Execution)'     │   '**9.7±0.43µs**'   │    '80.6±15.17µs'    │   '-88'    │
│   37    │       'RegExp Literal Creation (Full)'       │ '**284.7±14.13µs**'  │   '368.7±13.98µs'    │   '-22'    |
```

**Comment by HalidOdat** [comment]
Why are there old commit changes showing?

**Comment by neeldug** [comment]
I ran a rebase since the criterion versions were mismatched causing benchmarking to fail

**Comment by HalidOdat** [comment]
> I ran a rebase since the criterion versions were mismatched causing benchmarking to fail

strange , I think changing the merge base to a different one and back to master may fix this

**Comment by RageKnify** [comment]
I think creating a new branch from `master`, cherry-picking the original 5 `commit`s onto it. And opening a new PR might me an easier solution, there's not much discussion to be lost anyways and the new PR can mention this one. What do you think @HalidOdat ?

**Comment by neeldug** [comment]
@RageKnify it seems to be sorted now though?

**Comment by RageKnify** [comment]
GitHub seems to think we're merging 11 `commit`s into `master` and that's not the case at all. There are only 5 new `commit`s and a 6th one for merging (which could not exist if a new branch was made). I think in blame it will all point to this PR, but I still don't like it.

**Comment by HalidOdat** [comment]
> GitHub seems to think we're merging 11 `commit`s into `master` and that's not the case at all. There are only 5 new `commit`s and a 6th one for merging (which could not exist if a new branch was made). I think in blame it will all point to this PR, but I still don't like it.

This shouldn't be a problem since we always squash and merge the PRs into master so, on the master branch all the changes will be represented by one commit (`Implement regress fixes #478 (#686)` the PR title)

**Comment by RageKnify** [comment]
@neeldug resolve the conflicts when you can please

**Comment by neeldug** [comment]
@RageKnify accidentally deleted fork while this PR was active, have created a new PR with all of the previous commits at #774

**Pull request closed without merging**
