### PR TITLE
[Merged by Bors] - Implement `JsPromise` wrapper

### LINKED ISSUE #2687: Safe wrapper for `JsPromise`

### PR DESCRIPTION
**Pull request by jedel1043**
This Pull Request closes #2687.

It changes the following:

- Adds a `JsPromise` wrapper to manipulate promises from Rust.
- Cleans up the `promise` module to ease the integration of `JsPromise` with it.

cc @lastmjs

### CODE REVIEW

**Comment by nekevss** [comment]
This is great! On other built-in wrappers, I believe an example was typically added to `boa_example` to provide a basic reference outside of the docs. Any thought on doing adding that to this PR? Given the size, we could always file it as an issue, since implementing an example of `JsPromise` might be a great first issue for someone.

**Comment by jedel1043** [comment]
> Given the size, we could always file it as an issue, since implementing an example of `JsPromise` might be a great first issue for someone.

Sounds good! I think it's better to have some low hanging fruit to introduce new contributors to the repo, and adding an usage example sounds like the perfect issue for that. I'll open an issue for that after we merge this.

**Review by nekevss — APPROVED** [review]
Looks good to me! 😄 Nice work!

**Comment by jedel1043** [comment]
Yep! Some usage examples:

To move the microtask queue forward:

```rust
context.run_jobs();
```

To create a new, pending promise:

```rust
let (promise, resolvers) = JsPromise::new_pending(context);
```

To resolve a promise:

```rust
resolvers.resolve(this, &[value], context)?;

// or

resolvers.reject(this, &[error], context)?;
```

To inspect the state of a promise:

```rust
match promise.state() {
    PromiseState::Pending => {},
    PromiseState::Fulfilled(v) => {},
    PromiseState::Rejected(e) => {},
}
```

The `JsPromise` docs has more detailed examples :)

**Pull request closed without merging**
