### PR TITLE
Temporal: Build out `Time` and its methods

### PR DESCRIPTION
**Pull request by nekevss**
This Pull Request is related to the ongoing work on #1804. Mostly the work here is around building out more of the `Time` component and it's methods.

It changes the following:

- Adds/fixes `Duration`'s `is_date_duration` and `is_time_duration` methods (exposes them as public too)
- Adds accessor methods to `Time` component
- Adds the `Add`, `Subtract`, and `Round` methods along with implementation details
- Some tests for the above

### CODE REVIEW

**Review by raskad — APPROVED** [review]
Looks good

**Review by jasonwilliams — APPROVED** [review]
LGTM

**Review by jasonwilliams — APPROVED** [review]
LGTM

**Review by HalidOdat — APPROVED** [review]
Looks good to me! :)

**Pull request merged**
