### PR TITLE
[Merged by Bors] - Implement Object.prototype.__lookupSetter__

### LINKED ISSUE #2067: Implement legacy `Object.prototype` properties
The following `Object.prototype` properties are marked as optional and legacy in the spec but we should implement them to pass the corresponding 262 tests.

- [x] [Object.prototype.\_\_proto__](https://tc39.es/ecma262/#sec-object.prototype.__proto__)
- [x] [Object.prototype.\_\_defineGetter__](https://tc39.es/ecma262/#sec-object.prototype.__defineGetter__)
- [x] [Object.prototype.\_\_defineSetter__](https://tc39.es/ecma262/#sec-object.prototype.__defineSetter__)
- [x] [Object.prototype.\_\_lookupGetter__](https://tc39.es/ecma262/#sec-object.prototype.__lookupGetter__)
- [ ] [Object.prototype.\_\_lookupSetter__](https://tc39.es/ecma262/#sec-object.prototype.__lookupSetter__)

### PR DESCRIPTION
**Pull request by Sorck**
This Pull Request closes #2067

It changes the following:

- Implement `Object.prototype.__lookupSetter__`

This passes all tests from `./test262/test/built-ins/Object/prototype/__lookupSetter__/`

```
Loading the test suite...
Test suite loaded, starting tests...
Suite __lookupSetter__:
`lookup-own-get-err` (strict mode): starting
`lookup-own-get-err` (strict mode): Passed
`lookup-own-get-err`: starting
`lookup-own-get-err`: Passed
`length` (strict mode): starting
`length` (strict mode): Passed
`length`: starting
`length`: Passed
`lookup-proto-proto-err` (strict mode): starting
`lookup-proto-proto-err` (strict mode): Passed
`lookup-proto-proto-err`: starting
`lookup-proto-proto-err`: Passed
`lookup-own-acsr-wo-setter` (strict mode): starting
`lookup-own-acsr-wo-setter` (strict mode): Passed
`lookup-own-acsr-wo-setter`: starting
`lookup-own-acsr-wo-setter`: Passed
`lookup-not-found` (strict mode): starting
`lookup-not-found` (strict mode): Passed
`lookup-not-found`: starting
`lookup-not-found`: Passed
`lookup-proto-acsr-wo-setter` (strict mode): starting
`lookup-proto-acsr-wo-setter` (strict mode): Passed
`lookup-proto-acsr-wo-setter`: starting
`lookup-proto-acsr-wo-setter`: Passed
`lookup-proto-acsr-w-setter` (strict mode): starting
`lookup-proto-acsr-w-setter` (strict mode): Passed
`lookup-proto-acsr-w-setter`: starting
`lookup-proto-acsr-w-setter`: Passed
`name` (strict mode): starting
`name` (strict mode): Passed
`name`: starting
`name`: Passed
`lookup-own-acsr-w-setter` (strict mode): starting
`lookup-own-acsr-w-setter` (strict mode): Passed
`lookup-own-acsr-w-setter`: starting
`lookup-own-acsr-w-setter`: Passed
`lookup-own-proto-err` (strict mode): starting
`lookup-own-proto-err` (strict mode): Passed
`lookup-own-proto-err`: starting
`lookup-own-proto-err`: Passed
`lookup-proto-data` (strict mode): starting
`lookup-proto-data` (strict mode): Passed
`lookup-proto-data`: starting
`lookup-proto-data`: Passed
`lookup-own-data` (strict mode): starting
`lookup-own-data` (strict mode): Passed
`lookup-own-data`: starting
`lookup-own-data`: Passed
`lookup-proto-get-err` (strict mode): starting
`lookup-proto-get-err` (strict mode): Passed
`lookup-proto-get-err`: starting
`lookup-proto-get-err`: Passed
`prop-desc` (strict mode): starting
`prop-desc` (strict mode): Passed
`prop-desc`: starting
`prop-desc`: Passed
`key-invalid` (strict mode): starting
`key-invalid` (strict mode): Passed
`key-invalid`: starting
`key-invalid`: Passed
`this-non-obj` (strict mode): starting
`this-non-obj` (strict mode): Passed
`this-non-obj`: starting
`this-non-obj`: Passed

Suite __lookupSetter__ results: total: 32, passed: 32, ignored: 0, failed: 0 (panics: 0), conformance: 100.00%

Results:
Total tests: 32
Passed tests: 32
Ignored tests: 0
Failed tests: 0 (panics: 0)
Conformance: 100.00%
```

### CODE REVIEW

**Comment by Razican** [comment]
I think this is the last remaining bit, right?

**Comment by raskad** [comment]
#### VM implementation
  | Test result | main count | PR count | difference |
  | :---------: | :----------: | :------: | :--------: |
  | Total | 90,499 | 90,499 | 0 |
  | Passed | 56,446 | 56,482 | **+36** |
  | Ignored | 23,580 | 23,580 | 0 |
  | Failed | 10,473 | 10,437 | **-36** |
  | Panics | 0 | 0 | 0 |
  | Conformance | 62.37% | 62.41% | **+0.04%** |
  
  <details><summary><b>Fixed tests (36):</b></summary>
  
  ```
  test/built-ins/Object/prototype/__lookupSetter__/key-invalid.js [strict mode] (previously Failed)
  test/built-ins/Object/prototype/__lookupSetter__/key-invalid.js (previously Failed)
  test/built-ins/Object/prototype/__lookupSetter__/lookup-own-data.js [strict mode] (previously Failed)
  test/built-ins/Object/prototype/__lookupSetter__/lookup-own-data.js (previously Failed)
  test/built-ins/Object/prototype/__lookupSetter__/lookup-proto-acsr-wo-setter.js [strict mode] (previously Failed)
  test/built-ins/Object/prototype/__lookupSetter__/lookup-proto-acsr-wo-setter.js (previously Failed)
  test/built-ins/Object/prototype/__lookupSetter__/this-non-obj.js [strict mode] (previously Failed)
  test/built-ins/Object/prototype/__lookupSetter__/this-non-obj.js (previously Failed)
  test/built-ins/Object/prototype/__lookupSetter__/lookup-proto-get-err.js [strict mode] (previously Failed)
  test/built-ins/Object/prototype/__lookupSetter__/lookup-proto-get-err.js (previously Failed)
  test/built-ins/Object/prototype/__lookupSetter__/length.js [strict mode] (previously Failed)
  test/built-ins/Object/prototype/__lookupSetter__/length.js (previously Failed)
  test/built-ins/Object/prototype/__lookupSetter__/lookup-own-get-err.js [strict mode] (previously Failed)
  test/built-ins/Object/prototype/__lookupSetter__/lookup-own-get-err.js (previously Failed)
  test/built-ins/Object/prototype/__lookupSetter__/name.js [strict mode] (previously Failed)
  test/built-ins/Object/prototype/__lookupSetter__/name.js (previously Failed)
  test/built-ins/Object/prototype/__lookupSetter__/prop-desc.js [strict mode] (previously Failed)
  test/built-ins/Object/prototype/__lookupSetter__/prop-desc.js (previously Failed)
  test/built-ins/Object/prototype/__lookupSetter__/lookup-own-proto-err.js [strict mode] (previously Failed)
  test/built-ins/Object/prototype/__lookupSetter__/lookup-own-proto-err.js (previously Failed)
  test/built-ins/Object/prototype/__lookupSetter__/lookup-not-found.js [strict mode] (previously Failed)
  test/built-ins/Object/prototype/__lookupSetter__/lookup-not-found.js (previously Failed)
  test/built-ins/Object/prototype/__lookupSetter__/lookup-proto-data.js [strict mode] (previously Failed)
  test/built-ins/Object/prototype/__lookupSetter__/lookup-proto-data.js (previously Failed)
  test/built-ins/Object/prototype/__lookupSetter__/lookup-proto-proto-err.js [strict mode] (previously Failed)
  test/built-ins/Object/prototype/__lookupSetter__/lookup-proto-proto-err.js (previously Failed)
  test/built-ins/Object/prototype/__lookupSetter__/lookup-own-acsr-wo-setter.js [strict mode] (previously Failed)
  test/built-ins/Object/prototype/__lookupSetter__/lookup-own-acsr-wo-setter.js (previously Failed)
  test/built-ins/Object/prototype/__lookupSetter__/lookup-own-acsr-w-setter.js [strict mode] (previously Failed)
  test/built-ins/Object/prototype/__lookupSetter__/lookup-own-acsr-w-setter.js (previously Failed)
  test/built-ins/Object/prototype/__lookupSetter__/lookup-proto-acsr-w-setter.js [strict mode] (previously Failed)
  test/built-ins/Object/prototype/__lookupSetter__/lookup-proto-acsr-w-setter.js (previously Failed)
  test/language/expressions/class/elements/private-setter-is-not-a-own-property.js [strict mode] (previously Failed)
  test/language/expressions/class/elements/private-setter-is-not-a-own-property.js (previously Failed)
  test/language/statements/class/elements/private-setter-is-not-a-own-property.js [strict mode] (previously Failed)
  test/language/statements/class/elements/private-setter-is-not-a-own-property.js (previously Failed)
  ```
  </details>

**Review by raskad — APPROVED** [review]
Looks great. Only needs a rebase on main and then we are ready to merge.

**Comment by raskad** [comment]
> I think this is the last remaining bit, right?

Yes, this closes #2067

**Comment by jedel1043** [comment]
Edited the description to make bors close the issue automatically

**Comment by Sorck** [comment]
> Looks great. Only needs a rebase on main and then we are ready to merge.

Rebased against main.

**Review by jedel1043 — APPROVED** [review]

**Pull request closed without merging**
