### PR TITLE
[Merged by Bors] - Optimize Get/SetPropertyByName

### PR DESCRIPTION
**Pull request by tunz**
Similar to #2604, `GetPropertyByName`/`SetPropertyByName` has only string property key. So, we can skip index and utf16 conversions.

This improves QuickJS benchmark score 5.8% on average.
Richards: 37.0 -> 41.2
DeltaBlue: 38.1 -> 41.4
Crypto: 59.6 -> 59.8
RayTrace: 146 -> 159
EarleyBoyer: 138 -> 142
Splay: 104 -> 106
NavierStokes: 10.2 -> 10.3

### CODE REVIEW

**Review by jedel1043 — APPROVED** [review]
Thanks! Also, I'm seeing that you do additional benchmarking on the engine for every one of your PRs. Would you be open to integrate that on our repo?

**Review by raskad — APPROVED** [review]

**Comment by raskad** [comment]
bors retry

**Comment by tunz** [comment]
> Thanks! Also, I'm seeing that you do additional benchmarking on the engine for every one of your PRs. Would you be open to integrate that on our repo?

yeah, it would be nice to have the benchmark in CI, or regular run on any pipeline here. But, I'm not familiar with how the CI works here and how I can test it. I simply downloaded the [benchmark](https://bellard.org/quickjs/quickjs-extras-2021-03-27.tar.xz) and combined the tests by running `make` after removing RegExp test which was not working with `boa` at the time.

**Pull request closed without merging**
