### PR TITLE
Return function execution result from constructor if the function returned

### PR DESCRIPTION
**Pull request by raskad**
It changes the following:

- Return function execution result from constructor if the function returned
- Fix `Construct` calls in RegExp

### CODE REVIEW

**Comment by raskad** [comment]
The broken test `test/language/statements/function/S13.2.2_A14.js` previously passed because of the wrong reason. It actually requires `eval` to be implemented and should not pass right now.

### Test262 conformance changes:
  | Test result | master count | PR count | difference |
  | :---------: | :----------: | :------: | :--------: |
  | Total | 78,897 | 78,897 | 0 |
  | Passed | 29,633 | 29,710 | **+77** |
  | Ignored | 15,612 | 15,612 | 0 |
  | Failed | 33,652 | 33,575 | **-77** |
  | Panics | 2 | 2 | 0 |
  | Conformance | 37.56% | 37.66% | **+0.10%** |
  
  <details><summary><b>Fixed tests:</b></summary>
  
  ```
  test/built-ins/Function/15.3.5.4_2-16gs.js (previously Failed)
  test/built-ins/Function/15.3.5.4_2-18gs.js (previously Failed)
  test/built-ins/RegExp/prototype/Symbol.split/str-get-lastindex-err.js [strict mode] (previously Failed)
  test/built-ins/RegExp/prototype/Symbol.split/str-get-lastindex-err.js (previously Failed)
  test/built-ins/RegExp/prototype/Symbol.split/str-coerce-lastindex.js [strict mode] (previously Failed)
  test/built-ins/RegExp/prototype/Symbol.split/str-coerce-lastindex.js (previously Failed)
  test/built-ins/RegExp/prototype/Symbol.split/limit-0-bail.js [strict mode] (previously Failed)
  test/built-ins/RegExp/prototype/Symbol.split/limit-0-bail.js (previously Failed)
  test/built-ins/RegExp/prototype/Symbol.split/coerce-flags.js [strict mode] (previously Failed)
  test/built-ins/RegExp/prototype/Symbol.split/coerce-flags.js (previously Failed)
  test/built-ins/RegExp/prototype/Symbol.split/str-empty-match-err.js [strict mode] (previously Failed)
  test/built-ins/RegExp/prototype/Symbol.split/str-empty-match-err.js (previously Failed)
  test/built-ins/RegExp/prototype/Symbol.split/str-result-get-length-err.js [strict mode] (previously Failed)
  test/built-ins/RegExp/prototype/Symbol.split/str-result-get-length-err.js (previously Failed)
  test/built-ins/RegExp/prototype/Symbol.split/str-set-lastindex-err.js [strict mode] (previously Failed)
  test/built-ins/RegExp/prototype/Symbol.split/str-set-lastindex-err.js (previously Failed)
  test/built-ins/RegExp/prototype/Symbol.split/str-result-coerce-length-err.js [strict mode] (previously Failed)
  test/built-ins/RegExp/prototype/Symbol.split/str-result-coerce-length-err.js (previously Failed)
  test/built-ins/RegExp/prototype/Symbol.split/str-match-err.js [strict mode] (previously Failed)
  test/built-ins/RegExp/prototype/Symbol.split/str-match-err.js (previously Failed)
  test/built-ins/RegExp/prototype/Symbol.split/species-ctor-y.js [strict mode] (previously Failed)
  test/built-ins/RegExp/prototype/Symbol.split/species-ctor-y.js (previously Failed)
  test/built-ins/RegExp/prototype/Symbol.split/str-result-coerce-length.js [strict mode] (previously Failed)
  test/built-ins/RegExp/prototype/Symbol.split/str-result-coerce-length.js (previously Failed)
  test/built-ins/RegExp/prototype/Symbol.split/species-ctor.js [strict mode] (previously Failed)
  test/built-ins/RegExp/prototype/Symbol.split/species-ctor.js (previously Failed)
  test/built-ins/RegExp/prototype/Symbol.split/species-ctor-err.js [strict mode] (previously Failed)
  test/built-ins/RegExp/prototype/Symbol.split/species-ctor-err.js (previously Failed)
  test/built-ins/RegExp/prototype/Symbol.split/str-set-lastindex-no-match.js [strict mode] (previously Failed)
  test/built-ins/RegExp/prototype/Symbol.split/str-set-lastindex-no-match.js (previously Failed)
  test/built-ins/RegExp/prototype/Symbol.split/str-set-lastindex-match.js [strict mode] (previously Failed)
  test/built-ins/RegExp/prototype/Symbol.split/str-set-lastindex-match.js (previously Failed)
  test/built-ins/RegExp/prototype/Symbol.split/str-coerce-lastindex-err.js [strict mode] (previously Failed)
  test/built-ins/RegExp/prototype/Symbol.split/str-coerce-lastindex-err.js (previously Failed)
  test/built-ins/RegExp/prototype/Symbol.split/str-result-get-capture-err.js [strict mode] (previously Failed)
  test/built-ins/RegExp/prototype/Symbol.split/str-result-get-capture-err.js (previously Failed)
  test/built-ins/Array/prototype/map/create-species-abrupt.js [strict mode] (previously Failed)
  test/built-ins/Array/prototype/map/create-species-abrupt.js (previously Failed)
  test/built-ins/Array/prototype/map/create-species.js [strict mode] (previously Failed)
  test/built-ins/Array/prototype/map/create-species.js (previously Failed)
  test/built-ins/Array/prototype/map/target-array-non-extensible.js [strict mode] (previously Failed)
  test/built-ins/Array/prototype/map/target-array-non-extensible.js (previously Failed)
  test/built-ins/Array/prototype/slice/create-species-abrupt.js [strict mode] (previously Failed)
  test/built-ins/Array/prototype/slice/create-species-abrupt.js (previously Failed)
  test/built-ins/Array/prototype/slice/create-species.js [strict mode] (previously Failed)
  test/built-ins/Array/prototype/slice/create-species.js (previously Failed)
  test/built-ins/Array/prototype/slice/target-array-non-extensible.js [strict mode] (previously Failed)
  test/built-ins/Array/prototype/slice/target-array-non-extensible.js (previously Failed)
  test/built-ins/Array/prototype/flatMap/target-array-non-extensible.js [strict mode] (previously Failed)
  test/built-ins/Array/prototype/flatMap/target-array-non-extensible.js (previously Failed)
  test/built-ins/Array/prototype/concat/create-species-non-extensible.js [strict mode] (previously Failed)
  test/built-ins/Array/prototype/concat/create-species-non-extensible.js (previously Failed)
  test/built-ins/Array/prototype/concat/create-species-abrupt.js [strict mode] (previously Failed)
  test/built-ins/Array/prototype/concat/create-species-abrupt.js (previously Failed)
  test/built-ins/Array/prototype/concat/create-species.js [strict mode] (previously Failed)
  test/built-ins/Array/prototype/concat/create-species.js (previously Failed)
  test/built-ins/Array/prototype/concat/create-species-non-extensible-spreadable.js [strict mode] (previously Failed)
  test/built-ins/Array/prototype/concat/create-species-non-extensible-spreadable.js (previously Failed)
  test/built-ins/Array/prototype/flat/target-array-non-extensible.js [strict mode] (previously Failed)
  test/built-ins/Array/prototype/flat/target-array-non-extensible.js (previously Failed)
  test/built-ins/Array/prototype/filter/create-species-abrupt.js [strict mode] (previously Failed)
  test/built-ins/Array/prototype/filter/create-species-abrupt.js (previously Failed)
  test/built-ins/Array/prototype/filter/create-species.js [strict mode] (previously Failed)
  test/built-ins/Array/prototype/filter/create-species.js (previously Failed)
  test/built-ins/Array/prototype/filter/target-array-non-extensible.js [strict mode] (previously Failed)
  test/built-ins/Array/prototype/filter/target-array-non-extensible.js (previously Failed)
  test/built-ins/Array/of/return-abrupt-from-contructor.js [strict mode] (previously Failed)
  test/built-ins/Array/of/return-abrupt-from-contructor.js (previously Failed)
  test/built-ins/Array/of/return-abrupt-from-data-property.js [strict mode] (previously Failed)
  test/built-ins/Array/of/return-abrupt-from-data-property.js (previously Failed)
  test/language/arguments-object/S10.1.6_A1_T2.js [strict mode] (previously Failed)
  test/language/arguments-object/S10.1.6_A1_T2.js (previously Failed)
  test/language/statements/function/S13.2.2_A13.js [strict mode] (previously Failed)
  test/language/statements/function/S13.2.2_A13.js (previously Failed)
  test/language/statements/function/S13.2.2_A11.js [strict mode] (previously Failed)
  test/language/statements/function/S13.2.2_A11.js (previously Failed)
  test/language/statements/function/S13.2.2_A9.js [strict mode] (previously Failed)
  test/language/statements/function/S13.2.2_A9.js (previously Failed)
  ```
  </details>
  
  <details><summary><b>Broken tests:</b></summary>
  
  ```
  test/language/statements/function/S13.2.2_A14.js (previously Passed)
  ```
  </details>

**Comment by raskad** [comment]
@HalidOdat I think that cancelled ci job was just a fluke?

**Review by RageKnify — APPROVED** [review]

**Review by HalidOdat — APPROVED** [review]

**Comment by raskad** [comment]
@HalidOdat Seems like this just caused master be break, as there are some `Value`s instead of `JsValue`s in here. Do you want to revert this? I can fix this on this branch if you want.

**Comment by HalidOdat** [comment]
> @HalidOdat Seems like this just caused master be break, as there are some `Value`s instead of `JsValue`s in here. Do you want to revert this? I can fix this on this branch if you want.

It's Ok, committed compilation error fix on master branch

**Pull request merged**
