### PR TITLE
Implement functions for vm

### LINKED ISSUE #1430: Implement function declaration on VM
@HalidOdat as the VM doesn't support function declarations yet do you have any idea in mind how we would do this?
im guessing a new code block would need to be created and instructions within that function would need to be added to `code_block.code`.

We would need a stack to hold `code_block`s and switch over to one when calling the function

### PR DESCRIPTION
**Pull request by HalidOdat**
This Pull Request fixes/closes #1430 .

It changes the following:
- Implement compilation of `declaration`,`expression` and `arrow` functions
- Implement calling functions for vm.
- Implement calling vm function from rust side `.call()`
- Implement stack unwinding.
- Implement stack size limit (because of the non-compliant way we call functions this currently does not work, need to fix that first).

Now we can run code like
```js
function double(a) {
	return a * a;
}
[1, 2, 3, 4]["reverse"]().forEach((e) => {
	console.log(double(e));
});
```

### CODE REVIEW

**Comment by HalidOdat** [comment]
I'll try to rebase this today :)

**Review by RageKnify — APPROVED** [review]

**Comment by HalidOdat** [comment]
I'll try to rebase this today :)

**Review by raskad — APPROVED** [review]
I'm not that knowledgeable about the vm (yet), but from what I can see this looks sound.
I like the restructuring of `Vm`, `CallFrame` and `CodeBlock`.

There are some unresolved docs links in `boa/src/object/function.rs` you may want to fix.

**Review by jasonwilliams — APPROVED** [review]

**Comment by jasonwilliams** [comment]
Im going to merge this, its had approvals and looks good to me,

**Review by jasonwilliams — APPROVED** [review]

**Review by jasonwilliams — APPROVED** [review]

**Review by jasonwilliams — APPROVED** [review]

**Review by jasonwilliams — APPROVED** [review]

**Pull request merged**
