### PR TITLE
[Merged by Bors] - Switch tarpaulin to llvm engine

### PR DESCRIPTION
**Pull request by RageKnify**
Trying this to see if it makes coverage numbers more accurate

### CODE REVIEW

**Comment by RageKnify** [comment]
Both engines seem to mostly suffer from false negatives, this engine seems to considers 10139 more lines. Looking at the codecov.io report the differences are a little weird so I'm not sure how to feel.
Just because of this one reporting on more lines I tend to preffer it, but I want to hear others' opinion on this.
CC: @Razican @raskad @jedel1043 @HalidOdat @jasonwilliams

**Comment by raskad** [comment]
After reading the relevant issue in `tarpaulin`, my understanding is that the long term plan is to use `llvm` instead of `ptrace`. From that point of view it makes sense to me to switch over. I looked trough the report diff a bit and to me it seems like the `llvm` engine is more accurate in the lines it reports a covered.

I am in favor of switching.

**Comment by jedel1043** [comment]
I agree with @raskad. The LLVM backend also has the advantage of having more support for other architectures.

**Review by HalidOdat — APPROVED** [review]
Agreed, switching, to me seems like the right choice :)

**Review by Razican — APPROVED** [review]
I like the change :) tarpaulin is moving in the good direction here. If we find false positives/negatives, we should report them.

**Comment by Razican** [comment]
Bors r+

**Pull request closed without merging**
