### PR TITLE
Replace `js_str` with `js_string` in examples

### PR DESCRIPTION
**Pull request by getong**
It changes the following:

-  replace js_str with js_string in the example code

### CODE REVIEW

**Comment by HalidOdat** [comment]
> The js_str is deprecated

What is meant by this? `js_str` just landed on main yesterday...

**Comment by getong** [comment]
> > The js_str is deprecated
> 
> What is meant by this? `js_str` just landed on main yesterday...
> 
> EDIT: BTW I'm fine with replacing them with `js_string` since they are converted to `JsString` immediately in the examples.

Sorry for the info, just replace js_str with js_string

**Comment by getong** [comment]
rebase to main branch, which fix clippy warning

**Comment by getong** [comment]
https://github.com/getong/boa/pull/1
All the test have passed

**Review by jedel1043 — APPROVED** [review]
Thank you for the contribution!

**Review by HalidOdat — APPROVED** [review]

**Pull request merged**
