### PR TITLE
[Merged by Bors] - Fix regex literal /[/]/

### PR DESCRIPTION
**Pull request by tunz**
This PR fixes a case where a forward slash is located in a regex class: `let regex = /[/]/;`. In this case, the forward slash should not close the regex literal.

This fixes `test/built-ins/RegExp/regexp-class-chars.js`

### CODE REVIEW

**Comment by raskad** [comment]
#### VM implementation
  | Test result | main count | PR count | difference |
  | :---------: | :----------: | :------: | :--------: |
  | Total | 91,733 | 91,733 | 0 |
  | Passed | 64,940 | 64,942 | **+2** |
  | Ignored | 16,580 | 16,580 | 0 |
  | Failed | 10,213 | 10,211 | **-2** |
  | Panics | 0 | 0 | 0 |
  | Conformance | 70.79% | 70.79% | **+0.00%** |
  
  <details><summary><b>Fixed tests (2):</b></summary>
  
  ```
  test/built-ins/RegExp/regexp-class-chars.js [strict mode] (previously Failed)
  test/built-ins/RegExp/regexp-class-chars.js (previously Failed)
  ```
  </details>

**Review by raskad — COMMENTED** [review]
Nice find. I think there is still a problem if an escaped `]` is placed before the end of the character class right?
`/[\]/]/` should be a valid regex but would not be lexed correctly with this approach.

**Comment by tunz** [comment]
@raskad Could you elaborate? I think there is no problem with `/[\]/]/`. The escaped `]` should be handled by the backslash pattern match (line 81).

**Comment by raskad** [comment]
> @raskad Could you elaborate? I think there is no problem with `/[\]/]/`. The escaped `]` should be handled by the backslash pattern match (line 81).

True, the error I was looking at is unrelated and only happens in the boa_cli.

**Review by raskad — APPROVED** [review]
Very nice fix, thank you!

**Review by Razican — APPROVED** [review]
Good catch! Thanks for the fix :)

**Comment by Razican** [comment]
Bors r+

**Pull request closed without merging**
