### PR TITLE
Fix integer parsing

### PR DESCRIPTION
**Pull request by nrabulinski**
This Pull Request makes it possible to continue with #1602 and also fixes some errors with parsing integers.

It changes the following:

- Instead of manually parsing and adding each character I use i128::from_str_radix, which is then converted to f64

~~Unanswered questions:~~

~~- What does the spec say about even larger numbers? I've tested NodeJS and Firefox and you can more or less get unlimited range, albeit anything that's larger than `Number.MAX_SAFE_INTEGER` is not represented exactly. With this solution, however, numbers get clamped to -1.7e+38 and 1.7e+38. I'm assuming fixing this would most likely require an overhaul of the number representation and parsing code.~~

### CODE REVIEW

**Comment by jedel1043** [comment]
> * What does the spec say about even larger numbers? I've tested NodeJS and Firefox and you can more or less get unlimited range, albeit anything that's larger than `Number.MAX_SAFE_INTEGER` is not represented exactly. With this solution, however, numbers get clamped to -1.7e+38 and 1.7e+38. I'm assuming fixing this would most likely require an overhaul of the number representation and parsing code.

Now that I think about it, couldn't we use `JsBigInt` to parse the string as a big int, then convert into an f64?

**Comment by nrabulinski** [comment]
Disregard my previous comment, I got confused :smile: but yes, we probably could use BigInt for that, should I look into this?

**Comment by jedel1043** [comment]
> Disregard my previous comment, I got confused 😄 but yes, we probably could use BigInt for that, should I look into this?

Please do!

**Comment by nrabulinski** [comment]
> Please do!

It seems to work correctly!

**Review by jedel1043 — APPROVED** [review]
Looks good to me! :D

**Comment by raskad** [comment]
### Test262 conformance changes:
  | Test result | master count | PR count | difference |
  | :---------: | :----------: | :------: | :--------: |
  | Total | 80,930 | 80,930 | 0 |
  | Passed | 33,313 | 33,317 | **+4** |
  | Ignored | 15,898 | 15,898 | 0 |
  | Failed | 31,719 | 31,715 | **-4** |
  | Panics | 0 | 0 | 0 |
  | Conformance | 41.16% | 41.17% | **+0.00%** |
  
  <details><summary><b>Fixed tests (4):</b></summary>
  
  ```
  test/built-ins/Number/prototype/toFixed/exactness.js [strict mode] (previously Failed)
  test/built-ins/Number/prototype/toFixed/exactness.js (previously Failed)
  test/built-ins/parseInt/S15.1.2.2_A7.2_T3.js [strict mode] (previously Failed)
  test/built-ins/parseInt/S15.1.2.2_A7.2_T3.js (previously Failed)
  ```
  </details>

**Review by raskad — APPROVED** [review]

**Pull request merged**
