### PR TITLE
Allow `true`, `false` and `null` in object patterns

### PR DESCRIPTION
**Pull request by jedel1043**
This Pull Request allows using certain valid keywords inside patterns.

### CODE REVIEW

**Comment by Razican** [comment]
It seems that there is no test for this in Test262, so we should probably add our own, and maybe add a test to Test262.

**Review by HalidOdat — APPROVED** [review]
Looks good to me! +1 for the tests to test262, if not then our own :)

**Comment by jedel1043** [comment]
> It seems that there is no test for this in Test262, so we should probably add our own, and maybe add a test to Test262.

Will add both a test here and a PR on Test262, just to avoid blocking this on that PR.

**Review by Razican — APPROVED** [review]
Thanks!

**Pull request merged**
