### PR TITLE
Temporal duration update and cleanup

### PR DESCRIPTION
**Pull request by nekevss**
Some more work on `temporal`, in a little bit of a smaller PR 😉 

Mostly just trying to do a bit of cleanup and small cleanups/refactors with the idea of beginning to migrate some of the temporal methods and structures into their own crates.

It changes the following:
- Updates and/or begins to update a couple of `Temporal.Duration`'s methods and abstracts to relatively recent changes to the specification.
- General nitpicky cleanups to begin isolating some Temporal APIs from Boa specifics (calendar impl's needing context)

Aside: are smaller PRs a bit more similar to this one going to be easier to manage even if they are relatively more unfinished? I'm trying to avoid the monstrosity that was the last PR.

### CODE REVIEW

**Comment by jedel1043** [comment]
Smaller PRs sound like the best way to work incrementally on temporal, so +1 to that.

**Comment by nekevss** [comment]
I'll try to do more frequent smaller updates then.

**Review by HalidOdat — APPROVED** [review]
Looks good! Just some minor nitpick! :)

**Review by jedel1043 — APPROVED** [review]
Nice work!

**Pull request merged**
