### PR TITLE
[Merged by Bors] - Fix Regex literal parsing in MemberExpression

### LINKED ISSUE #2327: syntax error of `/=/` when it's used in call expression arguments
**Describe the bug**

Similar to https://github.com/boa-dev/boa/issues/2148, when there is an RegExp literal `/=/` as a call argument, boa raises an syntax error.

**To Reproduce**

This JavaScript code reproduces the issue:
```javascript
fn(/=/);
```

**Expected behavior**

ReferenceError of `fn` is expected, but it shows an syntax error.
```
$ cat a.js
fn(/=/);
$ ./target/release/boa ./a.js
Uncaught "SyntaxError": "unexpected token '/=', primary expression at line 1, col 4"
```

**Build environment (please complete the following information):**

- OS: macos
- Version: main
- Target triple: aarch64-apple-darwin
- Rustc version: rustc 1.64.0 (a55dd71d5 2022-09-19)

### PR DESCRIPTION
**Pull request by tunz**
This Pull Request fixes/closes #2327 

It changes the following:
- set_goal(RegExp) for PrimaryExpression parsing

### CODE REVIEW

**Comment by Razican** [comment]
### Test262 conformance changes
  
  #### VM implementation
  | Test result | main count | PR count | difference |
  | :---------: | :----------: | :------: | :--------: |
  | Total | 92,399 | 92,399 | 0 |
  | Passed | 68,926 | 68,932 | **+6** |
  | Ignored | 17,228 | 17,228 | 0 |
  | Failed | 6,245 | 6,239 | **-6** |
  | Panics | 0 | 0 | 0 |
  | Conformance | 74.60% | 74.60% | **+0.01%** |
  
  <details><summary><b>Fixed tests (6):</b></summary>
  
  ```
  test/language/expressions/division/S11.5.2_A2.2_T1.js [strict mode] (previously Failed)
  test/language/expressions/division/S11.5.2_A2.2_T1.js (previously Failed)
  test/language/expressions/division/S11.5.2_A3_T1.5.js [strict mode] (previously Failed)
  test/language/expressions/division/S11.5.2_A3_T1.5.js (previously Failed)
  test/language/expressions/division/bigint-toprimitive.js [strict mode] (previously Failed)
  test/language/expressions/division/bigint-toprimitive.js (previously Failed)
  ```
  </details>

**Review by Razican — COMMENTED** [review]
Sorry for the delay in the review! It looks great. Would it be possible to add a Rust test for this?

**Review by RageKnify — APPROVED** [review]

**Review by Razican — APPROVED** [review]
Thanks! LGTM :)

**Pull request closed without merging**
