### PR TITLE
Fix single line comment lexing with CRLF line ending

### LINKED ISSUE #963: Incorret lexing of single line comments
Single line comments in files using CRLF line endings result in the rest of the file being ignored.

**To Reproduce**
Since a file is required the best way to demonstrate the bug is to run with the following file: `cargo run -- test.txt` [test.txt](https://github.com/boa-dev/boa/files/5683971/test.txt)
The file contains:
```
console.log('0')
// .
console.log('1')
```

**Expected behavior**
`boa` should output:
```
0
1
undefined
```
but instead we do not get the `1`

This is probably what caused us to not see an increase in the number of passing test262 tests, a lot of them are not being lexed correctly.

Identified by @tofpie in https://github.com/boa-dev/boa/pull/961#issuecomment-743921418

### PR DESCRIPTION
**Pull request by tofpie**
This Pull Request fixes #963.

It changes the following:

- Lexing of single line comment

### CODE REVIEW

**Comment by Lan2u** [comment]
Do you also need to update the multi-line comment code? 

I think your first idea of making the lexer always return LF for the end of a line would be the best course as it makes lexing (very slightly) more simple (relevant if in future more tokens are added).

**Comment by tofpie** [comment]
I tried, but the lexer for single line comment uses `peek()` and not `next_byte()`, so it did not work.

https://github.com/boa-dev/boa/blob/0c068cb35bfedb595cdad460b1380ae382807dde/boa/src/syntax/lexer/comment.rs#L33-L40

I did not see any issues in the lexer for multi-line comment.

**Review by Razican — APPROVED** [review]
This looks good :) thanks

**Comment by Razican** [comment]
Hmmm surprisingly, this made 6 tests fail, but maybe that's correct.

### Test262 conformance changes:
  | Test result | master count | PR count | difference |
  | :---------: | :----------: | :------: | :--------: |
  | Total | 78,460 | 78,460 | 0 |
  | Passed | 18,964 | 18,958 | **-6** |
  | Ignored | 15,559 | 15,559 | 0 |
  | Failed | 43,937 | 43,943 | **+6** |
  | Panics | 1,127 | 1,127 | 0 |
  | Conformance | 24.17 | 24.16 | **-0.01%** |

**Comment by tofpie** [comment]
I have run the tests before and after the fix on Linux using WSL, and I have checked some of the newly failed tests. In fact, it seems that even when using Linux, some files from the test262 repository contains CRLF line endings. So, tests that were previously passed because they were considered empty are now failed because they contain not yet supported features (such as eval).
On the other side, some tests that explicitly test the single line comment with CRLF, and are now passed.

**Pull request merged**
