### PR TITLE
Added examples

### LINKED ISSUE #2337: Add code examples for `boa_interner`
The `boa_interner` crate has an `allow(rustdoc::missing_doc_code_examples)` on its root. Ideally, this crate should have some usage snippets on every `pub` function.

### PR DESCRIPTION
**Pull request by postmeback**
This Pull Request fixes/closes #2337 

It changes the following:

Added two new functions to test `Interner::default();` & `Interner::with_capacity;`

Requesting for review

### CODE REVIEW

**Comment by postmeback** [comment]
Hey, Can this be added ?

**Comment by postmeback** [comment]
Can anyone tell me, how to fix this `rustfmt` error?

**Comment by Razican** [comment]
> Can anyone tell me, how to fix this `rustfmt` error?

You will need to run `cargo fmt` with the latest Rust stable.

**Comment by postmeback** [comment]
image

**Comment by postmeback** [comment]
Changed as per the lint suggestion

**Review by Razican — APPROVED** [review]

**Review by jedel1043 — APPROVED** [review]
Thank you!

**Comment by postmeback** [comment]
Thanks @Razican , @jedel1043

**Pull request merged**
