### PR TITLE
Don't consider panic fixes as "new failures"

### PR DESCRIPTION
**Pull request by Razican**
Previously, if a panic was fixed and it was now failing, it would be considered as a "new failure". This considers it a panic fix.

### CODE REVIEW

**Comment by Razican** [comment]
I also took the opportunity to improve a bit the code and update the Test262 suite.

**Comment by Razican** [comment]
It seems that the update of the Test262 submodule is breajing this, probably due to https://github.com/tc39/test262/commit/56ca8add7dbc1efe49e5456689ddeb57ef4e296a

**Comment by 0x7D2B** [comment]
Can you make it so that there's a way to tell apart tests that were panicking but now pass and tests that were panicking but now fail?

**Comment by Razican** [comment]
> Can you make it so that there's a way to tell apart tests that were panicking but now pass and tests that were panicking but now fail?

Something that can be done is to consider a Panic -> Passed a normal "fixed" test. In the list, it will show that it was panicking before.

**Comment by 0x7D2B** [comment]
I think we still want to know if a test that previously panicked now fails, since that's an improvement. Though if we get to zero panics and make sure to not merge anything that adds panics, we might not see this very often.

**Comment by Razican** [comment]
> I think we still want to know if a test that previously panicked now fails, since that's an improvement. Though if we get to zero panics and make sure to not merge anything that adds panics, we might not see this very often.

Yes, the idea would be that if a "Panic" goes to "Pass", it will be considered a "new passing test", but if it goes from "panic" to "Fail", then it would be considered a "panic fix".

**Comment by Razican** [comment]
This is ready for review. The extra panic seems this panic that happens only "sometimes". I'm unable to reproduce it locally.

**Review by 0x7D2B — APPROVED** [review]

**Review by RageKnify — APPROVED** [review]

**Pull request merged**
