### PR TITLE
[Merged by Bors] - Started adding the [[Done]] field to iterators

### PR DESCRIPTION
**Pull request by Razican**
This Pull Request adds the `[[Done]]` field to iterator records.

### CODE REVIEW

**Comment by Razican** [comment]
I am probably missing stuff on the VM, but I'm somehow not able to make this work :(

**Comment by raskad** [comment]
I got the vm code to work. Only a few tests are missing. I'm currently looking into those.

One big change is, that the `[[NextMethod]]` can be a value instead of an object. Imo the spec is just wrong with the field description of `[[NextMethod]]`. It sounds like it can only be a function: [`a function object`](https://tc39.es/ecma262/#table-iterator-record-fields). But in [`GetIterator`](https://tc39.es/ecma262/#sec-getiterator) it clearly can be a value:
```txt
5. Let nextMethod be ? GetV(iterator, "next").
6. Let iteratorRecord be the Iterator Record { [[Iterator]]: iterator, [[NextMethod]]: nextMethod, [[Done]]: false }.
```

**Comment by Razican** [comment]
Thanks @raskad! I will now add the logic to the Promises :)

**Comment by Razican** [comment]
The two test failures are due to changes in Test262. Not related to the PR. I think this is ready for review :)

**Review by raskad — APPROVED** [review]
Looks good to me, if we want to include the dependency updates here.

**Review by jedel1043 — APPROVED** [review]
Looks good!

**Pull request closed without merging**
