### PR TITLE
Clippy updates: add panics and etc.

### PR DESCRIPTION
**Pull request by nekevss**
This Pull Request is related to the failing CI on #3232.

It changes the following:

- Adds the ` # Panics` doc to the drop method.

EDIT: This kind of went a bit farther than I intended initially to just about all the lints. Comment is below.

### CODE REVIEW

**Review by Razican — APPROVED** [review]
Thanks!

**Comment by nekevss** [comment]
Actually there's a lot more...clippy only feeds them one at a time apparently

**Comment by nekevss** [comment]
I updated a large amount of the lints in most the crates.

There were two lints that I didn't address and marked them as allow currently:

1. There's a `Send`/``Sync` not implemented on `Arc` lint that is currently triggering on the `Inner` of `JsSymbol`
2. There's A LOT of missing `Panics` docs in `boa_engine` (50+) so I ignored them for now.

I wasn't sure if we should add panic docs on those functions or create an issue to remove the panics entirely and throw something of an `ImplementationError` or something of the sort.

**Comment by Razican** [comment]
Se should at least have an issue for each of those. Ideally removing panics where possible.

**Review by jedel1043 — APPROVED** [review]

**Comment by jedel1043** [comment]
Will merge this since it's holding back some dep updates, but I also agree that we should open issues for the pending tasks.

**Comment by nekevss** [comment]
I'll submit the issues 😄

**Review by HalidOdat — APPROVED** [review]

**Pull request merged**
