### PR TITLE
Fix test suite name when it contains a dot

### LINKED ISSUE #984: boa_tester: Bad name for test suite containing a dot
**Describe the bug**
When the name of a test suite contains a dot, the part following the last dot is removed from its name.

**To Reproduce**
```
 cargo run --release --bin boa_tester -- run -s test/built-ins/Array/Symbol.species -v
    Finished release [optimized] target(s) in 0.16s
     Running `target\release\boa_tester.exe run -s test/built-ins/Array/Symbol.species -v`
Loading the test suite...
Test suite loaded, starting tests...
Suite Symbol:
........
Results: total: 8, passed: 0, ignored: 0, failed: 8 (panics: 0), conformance: 0.00%

Results:
Total tests: 8
Passed tests: 0
Ignored tests: 0
Failed tests: 8 (panics: 0)
Conformance: 0.00%
```

**Expected behavior**
The name of the test suite should be `Symbol.species`.

**Build environment (please complete the following information):**

- OS: Windows 10
- Version: 0.10
- Target triple: x86_64-pc-windows-msvc
- Rustc version: rustc 1.48.0 (7eac88abb 2020-11-16)

**Additional context**
None

### PR DESCRIPTION
**Pull request by tofpie**
This Pull Request fixes #984.

It changes the following:

- Test suite name generation

### CODE REVIEW

**Review by HalidOdat — APPROVED** [review]

**Review by RageKnify — APPROVED** [review]

**Comment by Razican** [comment]
I think this requires changes in the gh-pages branch to take it into account, right?

**Comment by tofpie** [comment]
Then, I need some guidance here. What changes would be required?

**Comment by Razican** [comment]
> Then, I need some guidance here. What changes would be required?

The `gh-pages` branch has a Test262 result representation in the `test262` folder. Since this changes the name of the tests, this will require a change in [here](https://github.com/boa-dev/boa/blob/gh-pages/test262/results.js#L223), since now the tests also include the `.js` in the name, right? This should allow properly opening the test file in the Test262 GitHub repo.

**Comment by tofpie** [comment]
> 
> 
> > Then, I need some guidance here. What changes would be required?
> 
> The `gh-pages` branch has a Test262 result representation in the `test262` folder. Since this changes the name of the tests, this will require a change in [here](https://github.com/boa-dev/boa/blob/gh-pages/test262/results.js#L223), since now the tests also include the `.js` in the name, right? This should allow properly opening the test file in the Test262 GitHub repo.

In fact, this modification only changes the names for the test suites, that is the name of the directories that contain the `.js` files, and not the name of the `.js` files. For the `.js` files, `file_stem()` is kept, so the `.js` suffix is removed as previously:
https://github.com/boa-dev/boa/blob/3b83767e58d9d20e9717bf2918098d7c92148482/boa_tester/src/read.rs#L149-L158

**Comment by Razican** [comment]
> In fact, this modification only changes the names for the test suites, that is the name of the directories that contain the `.js` files, and not the name of the `.js` files. For the `.js` files, `file_stem()` is kept, so the `.js` suffix is removed as previously:
> 
> https://github.com/boa-dev/boa/blob/3b83767e58d9d20e9717bf2918098d7c92148482/boa_tester/src/read.rs#L149-L158

Oh, true, that's perfect, yes! Let's merge it :)

**Review by Razican — APPROVED** [review]

**Pull request merged**
