### PR TITLE
[Merged by Bors] - Fix sync generator yield expressions

### PR DESCRIPTION
**Pull request by raskad**
Depends on #2837.

This Pull Request changes the following:

- Fix the remaining `language/expressions/yield` tests.
- Align the sync generator execution more to the spec.

This breaks one async generator test. We can ignore that one as async generators are currently very broken. I will try to fix async generators next.

### CODE REVIEW

**Review by HalidOdat — APPROVED** [review]
Looks good to me! :)

**Comment by nekevss** [comment]
Nice work! I like the changes overall, any idea why `yield-star-normal-notdone-iter-value-throws.js` broke?

**Comment by raskad** [comment]
> Nice work! I like the changes overall, any idea why `yield-star-normal-notdone-iter-value-throws.js` broke?

I did not look into it too much, because `yield*` in async generators is currently completely broken. But I think it's probably just the changes to where we create the iterator result objects.

I'm currently working on a fix for async generators and proper async generator `yield*`. My branch has 1000+ tests passing currently and I think I may be on a good way to actually fix all async generator tests.

**Review by nekevss — APPROVED** [review]
LGTM 😄

**Pull request closed without merging**
