### PR TITLE
[Merged by Bors] - Fix `TypedArray`s minus zero key

### PR DESCRIPTION
**Pull request by HalidOdat**
It changes the following:

- Fix `-0` index in typed arrays

### CODE REVIEW

**Comment by Razican** [comment]
Hmmm are those broken tests expected?

**Comment by HalidOdat** [comment]
> Hmmm are those broken tests expected?

I think this is caused because I need to check it's detached, converting this into a draft PR until it's fixed :)

**Comment by HalidOdat** [comment]
> I think this is caused because I need to check if it's detached first, converting this into a draft PR until it's fixed :)

Fixed! :)

**Review by Razican — APPROVED** [review]
Looks good to me!! Great comments explaining deviations from the spec :)

**Pull request closed without merging**
