### PR TITLE
Refactor conformance page

### PR DESCRIPTION
**Pull request by raskad**
This PR refactors the conformance page to hopefully be a bit more maintainable. The current js code is a bit confusing and hard to read IMO (nested functions, no async/await, jquery appends all over the place, ...). I tried to make it a bit more readable by dropping jquery in favor of some bigger template strings and native DOM apis. I also moved some html to the index.html file. Additionally I made some design adjustments to the page to make it look a bit more modern.

It's far from perfect, but let me know what you think.

### CODE REVIEW

**Comment by Razican** [comment]
Is there a screenshot?

**Comment by jedel1043** [comment]
> Is there a screenshot?

image
image

**Review by jedel1043 — CHANGES_REQUESTED** [review]
It mostly looks good! However, I'm pretty sure this undid the optimization of #2384. You can verify it by clicking the test results button for several versions of Boa. In my case, this lags my whole browser.

**Comment by raskad** [comment]
> I'm pretty sure this undid the optimization of https://github.com/boa-dev/boa/pull/2384. You can verify it by clicking the test results button for several versions of Boa. In my case, this lags my whole browser.

Very true. I checked the full html size and it was almost 30MB :D I changed the code to generate the html for the direct tests and inner suites lazily, only when each suite is shown.

The page is now very responsive for me, can you confirm @jedel1043?

**Review by jedel1043 — APPROVED** [review]
Yep, feels responsive for me. Nice change!

**Review by Razican — APPROVED** [review]

**Pull request merged**
