### PR TITLE
[Merged by Bors] - Fix double property access on assignment ops

### PR DESCRIPTION
**Pull request by raskad**
Currently the compilation of assignment operators leads to a double object property access, both on the get and set access.

While this refactor adds special access handling instead of using the existing `access_set` and `access_get` functions, it fixes the double access and should also make the resulting code more efficient.

### CODE REVIEW

**Comment by raskad** [comment]
> On another note, maybe we should split this function into `compile_simple_assign` and `compile_assign_op`, since they don't share any logic at all.

I thought this too. In the same change I would also refactor the AST to make it a bit typesafer. I'd like to push that in a follow up PR to keep the diff reasonable.

**Review by jedel1043 — APPROVED** [review]
Sounds good!

**Review by nekevss — APPROVED** [review]
Looks good to me 😄

**Pull request closed without merging**
