### PR TITLE
Fix clippy on Nightly

### PR DESCRIPTION
**Pull request by dvtkrlbs**
This PR just fixes clippy

It changes the following:
 - It changes match blocks that returns booleans with two arms and if let blocks to the matches! macro 

Ok i accidently tried this with nightly clippy and fixed a lint error for it. So this pr could be for nothing. But i can make it a draft PR and we can revisit it after this lint comes to the stable (if it ever does).

### CODE REVIEW

**Comment by Razican** [comment]
> Also why clippy is not enabled on CI?

Isn't it? I thought we had an specific test, that's odd.

**Comment by dvtkrlbs** [comment]
Oh there is. How come it was not failing for this lint ?

**Review by Lan2u — APPROVED** [review]

**Review by Lan2u — APPROVED** [review]
Approved but only once this is stable.

**Review by Razican — APPROVED** [review]
I'm happy to merge this as-is. The `matches!()` macro is already stable, it's the lint the only thing that is unstable, so merging this would future-proof the project. What do everyone else think?

**Comment by Lan2u** [comment]
> I'm happy to merge this as-is. The `matches!()` macro is already stable, it's the lint the only thing that is unstable, so merging this would future-proof the project. What do everyone else think?

If @dvtkrlbs can resolve the merge conflict then I'm happy to merge this

**Review by HalidOdat — APPROVED** [review]

**Pull request merged**
