### PR TITLE
bug fix: ops that stay strictly at the EOF after assigns ops are ignored

### LINKED ISSUE #3330: Slashes after assignments at the end of files are allowed
**Describe the bug**
If code in the form `<identifier> <assignment operator> <identifier> "/" <eof>` is passed to Boa, the code executes as if the "/" were not present; it should raise a SyntaxError.

This bug does not work if there are characters after the "/", including newlines or spaces. The "/" must be the last character in the input.

**To Reproduce**
In your shell, assuming GNU coreutils: `echo -n 'let a, b; a = b /' > test.js; boa test.js`
Note that `echo -n` is required to avoid a trailing newline.

**Expected behavior**
This code should throw a `SyntaxError`. The `/` character is unexpected and is not valid syntax.

**Build environment (please complete the following information):**

- OS: Artix Linux
- Version: rolling
- Target triple: `x86_64-unknown-linux-gnu`
- Rustc version: `rustc 1.72.1 (d5c2e9c34 2023-09-13)`

**Additional context**
This bug works with most if not all of the assignment operators. For example, neither `a /= b /` nor `a += b /` raise a `SyntaxError` despite being invalid JavaScript.

### PR DESCRIPTION
**Pull request by Nikita-str**
This Pull Request closes #3330 

The reason of the bug was that lexer decides next Token sequence {`...`, `OP`, `EOF`} as invalid and return an error. Yes, it's invalid, but in the same time lexer cannot know that {`...`, `OP`, `SPACE`, `EOF`} is also invalid and therefore there was two different logic to catch first case.

So, for me it seems more logically correct to delegate the catching of invalid ops at the end to the parser

-----

Should I:
* remove all `Ok(...)` from `core/parser/src/lexer/operator.rs` (now there exist only pseudo `Err(..)` that needs only for type inference)?
* use strum::EnumIter to remove enumeration of almost all `Punctuator`  in `core/parser/src/lexer/tests.rs`?

-----

Hmm... now I understand that I don't know the place where errors from lexer don't propagate upwards before, seems like somewhere not used `?`
Do I need to investigate where the place?

### CODE REVIEW

**Comment by raskad** [comment]
Hi @Nikita-str thank you for investigating this. I think the tests look good like this.

> Hmm... now I understand that I don't know the place where errors from lexer don't propagate upwards before, seems like somewhere not used ?
Do I need to investigate where the place?

I did a quick check and I'm pretty sure that the place is here: https://github.com/boa-dev/boa/blob/97c44239a4edadcaec086fbd28234ebec86eefcc/core/parser/src/parser/expression/assignment/mod.rs#L110-L111
The error is ignored, because we only want to check if an arrow function follows and there may be nothing there. If you can figure out a way to propagate the error there too with your fix, or rewrite that logic, that would be great.

**Comment by Nikita-str** [comment]
@raskad 
> I did a quick check and I'm pretty sure that the place is here: ...

Yeah, it is.
And just fix this line can resolve the issue, but as I say in the PR comment, it seems to me more correct to delegate catching of the error to parser. But maybe I'm wrong, so it's up for discussion.

---

Also, the problem here is that if we ignore some errors from lexer, like one that removed now from `core/parser/src/lexer/operator.rs` or `invalid regular expression flag`, the position of cursor will changed and we will get something new from `peek`/`next`.

In cur case on first call it is `Err(Lex { err: Syntax("abrupt end - could not preview next value as part of the operator", ...)})` and then (if we ignore the error) it will `Ok(None)`. This error always stay on the EOF, but with regex we can just ignore invalid regex in case of ignoring.

Thus maybe there is sense (not within this PR) to save an error in ?Lexer? and repeatedly return it?
(But you can not just clone an Error because of `IO(io::Error)`)

On the other hand, ignoring an error from lexer is error, but as you can see sometimes it's not noticeable.

**Comment by raskad** [comment]
> On the other hand, ignoring an error from lexer is error, but as you can see sometimes it's not noticeable.

I would say this is definitley the problem here. We should probably think about the lexer and the parser as two separate entities. For example, they probably could be different crates. From that perspective, there should be no logic that is spread across both (like holding on to an error in the lexer).

---

Can you rebase the branch, there are some conflicts now that prevent the CI from running. Did you get a chance to run the 262 tests locally with your latest commit? I would expect some tests to fail, because arrow functions would now be parsed with line terminators between the identifier and the arrow. Or am I missing something?

**Comment by Nikita-str** [comment]
Yes, you are right, there was some regression on test262, my bad.
Fixed

**Comment by raskad** [comment]
Looks very good, great work!

Now that everything works as expected, I think you can remove the `#[allow(unreachable_patterns)]` and the try branches, correct? Should be possible to remove the `?` where the `vop!` macro is called in the `op!` macro. Then all the `Ok` wrapping should be uneccessary. Then we can merge this.

**Review by raskad — APPROVED** [review]
Looks great, thank you for finding the issue :)

**Review by jedel1043 — APPROVED** [review]

**Pull request merged**
