### PR TITLE
Temporal: Initial `PlainTime` build out

### PR DESCRIPTION
**Pull request by nekevss**
This Pull Request is related to ongoing work for #1804.

Primarily plugs some of the implemented `boa_temporal`'s `Time` into `PlainTime` in the 

It changes the following:

- Adds `PlainTime` accessors and some methods
- Implements `to_temporal_duration_record`

### CODE REVIEW

**Review by raskad — APPROVED** [review]
Looks good

**Review by HalidOdat — COMMENTED** [review]
Looks good to me! :)

**Comment by raskad** [comment]
> Looks good to me! :)

@HalidOdat You only commented and not approved ;)

**Review by HalidOdat — APPROVED** [review]
> @HalidOdat You only commented and not approved ;)

Sorry, I meant to approve it :laughing:

**Pull request merged**
