### PR TITLE
feat: import parsing

### PR DESCRIPTION
**Pull request by afinch7**
Simple import statement parsing. I intend to follow this up with some execution implementation.

### CODE REVIEW

**Comment by jasonwilliams** [comment]
Thanks for picking this up

**Comment by jasonwilliams** [comment]
You need to rebase

**Comment by afinch7** [comment]
This isn't really spec compliant, but it works fine for the time being. Things like multiple default imports are parsed without error. This example isn't supposed to be valid, but it parses fine:
``` JavaScript
import default, defaultTwo from "./somefile.js";
```
I'm not to concerned with this currently. I would prefer to move on to export parsing and revisit this once module execution works.

**Comment by Razican** [comment]
Hi! The parser has changed a lot after #281. Would it be possible to rebase?

**Comment by jasonwilliams** [comment]
pings @afinch7 we may have to close this PR if it becomes inactive

**Comment by afinch7** [comment]
I should have some time this week to get this completely rebased.

**Comment by afinch7** [comment]
I haven't been able to find the time to rebase this right now. I'm closing for now.

**Pull request closed without merging**
