### PR TITLE
[Merged by Bors] - Add unicode terminator to line comment

### PR DESCRIPTION
**Pull request by creampnx-x**
This PR sloves the unicode terminator to single line comment
+ [{u+2028}](https://unicode-table.com/en/2028/)
+ [{u+2029}](https://unicode-table.com/en/2029/)
+ [related test](https://github.com/tc39/test262/blob/9215420deee3e5887d29f95822bf6a474c1bf728/test/language/line-terminators/comment-single-ps.js)
+ [related test set](https://github.com/tc39/test262/tree/9215420deee3e5887d29f95822bf6a474c1bf728/test/language/line-terminators)

### CODE REVIEW

**Comment by creampnx-x** [comment]
### Test262 conformance changes
  
  #### VM implementation
  | Test result | main count | PR count | difference |
  | :---------: | :----------: | :------: | :--------: |
  | Total | 92,057 | 92,057 | 0 |
  | Passed | 68,612 | 68,622 | **+10** |
  | Ignored | 16,832 | 16,832 | 0 |
  | Failed | 6,613 | 6,603 | **-10** |
  | Panics | 0 | 0 | 0 |
  | Conformance |74.53% | 74.54% | **+0.01%** |
  
  <details><summary><b>Fixed tests (10):</b></summary>
  
  ```
  test/language/line-terminators/comment-single-ps.js [strict mode] (previously Failed)
  test/language/line-terminators/comment-single-ps.js (previously Failed)
  test/language/line-terminators/comment-single-ls.js [strict mode] (previously Failed)
  test/language/line-terminators/comment-single-ls.js (previously Failed)
  test/language/line-terminators/invalid-comment-single-ls.js [strict mode] (previously Failed)
  test/language/line-terminators/invalid-comment-single-ls.js (previously Failed)
  test/language/line-terminators/invalid-comment-single-ps.js [strict mode] (previously Failed)
  test/language/line-terminators/invalid-comment-single-ps.js (previously Failed)
  test/language/comments/S7.4_A5.js [strict mode] (previously Failed)
  test/language/comments/S7.4_A5.js (previously Failed)
  ```
  </details>

**Review by raskad — APPROVED** [review]
Nice fix, thanks!

**Review by Razican — APPROVED** [review]
Thanks for the fix!

**Pull request closed without merging**
