### PR TITLE
Added `String`, `Boolean` and `Number` object benchmarks

### PR DESCRIPTION
**Pull request by HalidOdat**

### CODE REVIEW

**Comment by HalidOdat** [comment]
It seems `criterion-comapare-action` is failing with message:
```
TypeError: Cannot read property 'split' of undefined
```

**Comment by Razican** [comment]
> It seems `criterion-comapare-action` is failing with message :confused:
> ```
> TypeError: Cannot read property 'split' of undefined
> ``` 

Yep, this happens with new benchmarks. There is a PR in the repo that solves it.

**Comment by HalidOdat** [comment]
I'm re-running the benchmarks :)

**Comment by HalidOdat** [comment]
Another error criterion-comapare-action:
```
ReferenceError: difference is not defined
```

**Pull request merged**
