### PR TITLE
Implement `Array.prototype.sort`

### PR DESCRIPTION
**Pull request by jedel1043**
This Pull Request checks off a method from #36.

It changes the following:

- Implements the `Array.prototype.sort` method
- Implements tests for `Array.prototype.sort`

### CODE REVIEW

**Comment by Razican** [comment]
### Test262 conformance changes:
  | Test result | master count | PR count | difference |
  | :---------: | :----------: | :------: | :--------: |
  | Total | 78,897 | 78,897 | 0 |
  | Passed | 26,865 | 26,886 | **+21** |
  | Ignored | 15,628 | 15,628 | 0 |
  | Failed | 36,404 | 36,383 | **-21** |
  | Panics | 0 | 0 | 0 |
  | Conformance | 34.05% | 34.08% | **+0.03%** |
  
  <details><summary><b>Fixed tests:</b></summary>
  
  ```
  test/language/expressions/property-accessors/S11.2.1_A4_T4.js [strict mode] (previously Failed)
  test/language/expressions/property-accessors/S11.2.1_A4_T4.js (previously Failed)
  test/built-ins/Object/getOwnPropertyDescriptor/15.2.3.3-4-44.js [strict mode] (previously Failed)
  test/built-ins/Object/getOwnPropertyDescriptor/15.2.3.3-4-44.js (previously Failed)
  test/built-ins/Array/prototype/sort/S15.4.4.11_A4_T3.js [strict mode] (previously Failed)
  test/built-ins/Array/prototype/sort/S15.4.4.11_A4_T3.js (previously Failed)
  test/built-ins/Array/prototype/sort/S15.4.4.11_A1.2_T1.js [strict mode] (previously Failed)
  test/built-ins/Array/prototype/sort/S15.4.4.11_A1.2_T1.js (previously Failed)
  test/built-ins/Array/prototype/sort/S15.4.4.11_A8.js (previously Failed)
  test/built-ins/Array/prototype/sort/name.js [strict mode] (previously Failed)
  test/built-ins/Array/prototype/sort/name.js (previously Failed)
  test/built-ins/Array/prototype/sort/S15.4.4.11_A1.2_T2.js [strict mode] (previously Failed)
  test/built-ins/Array/prototype/sort/S15.4.4.11_A1.2_T2.js (previously Failed)
  test/built-ins/Array/prototype/sort/prop-desc.js [strict mode] (previously Failed)
  test/built-ins/Array/prototype/sort/prop-desc.js (previously Failed)
  test/built-ins/Array/prototype/sort/length.js [strict mode] (previously Failed)
  test/built-ins/Array/prototype/sort/length.js (previously Failed)
  test/built-ins/Array/prototype/sort/S15.4.4.11_A1.1_T1.js [strict mode] (previously Failed)
  test/built-ins/Array/prototype/sort/S15.4.4.11_A1.1_T1.js (previously Failed)
  test/built-ins/Array/prototype/sort/S15.4.4.11_A1.3_T1.js [strict mode] (previously Failed)
  test/built-ins/Array/prototype/sort/S15.4.4.11_A1.3_T1.js (previously Failed)
  ```
  </details>

**Comment by jedel1043** [comment]
@HalidOdat could you give it a quick review?

**Comment by jedel1043** [comment]
### Test262 conformance changes:
  | Test result | master count | PR count | difference |
  | :---------: | :----------: | :------: | :--------: |
  | Total | 78,897 | 78,897 | 0 |
  | Passed | 29,766 | 29,825 | **+59** |
  | Ignored | 15,612 | 15,612 | 0 |
  | Failed | 33,519 | 33,460 | **-59** |
  | Panics | 2 | 2 | 0 |
  | Conformance | 37.73% | 37.80% | **+0.07%** |

**Review by HalidOdat — APPROVED** [review]
Looks good to me :)

**Comment by jedel1043** [comment]
> Looks good to me :)

Nice! Let me rebase to merge it then 😄

**Review by HalidOdat — APPROVED** [review]

**Pull request merged**
