### PR TITLE
Remove references to dev docs and npm dependencies

### PR DESCRIPTION
**Pull request by jedel1043**
This should finally allow us to remove `gh-pages`, and free the repo from the 1GB of data on clones.

### CODE REVIEW

**Comment by jedel1043** [comment]
Broken test are unrelated, caused by #3783.

**Comment by HalidOdat** [comment]
Shouldn't we also delete `webpack.config.js`?

**Comment by jedel1043** [comment]
Oh, I deleted it locally but my IDE didn't stage the change. Let me fix that.

**Review by HalidOdat — APPROVED** [review]
Looks perfect to me! :)

**Pull request merged**
