### PR TITLE
Initial template literal lexer implementation

### PR DESCRIPTION
**Pull request by croraf**
Starting to implement. Would like this to be merged now.

### CODE REVIEW

**Comment by croraf** [comment]
I also slipped in a move of self.next() into the match of the lexer itself.

1 line of this I adjusted in first commit, and the rest in the second commit.

**Comment by croraf** [comment]
So this PR consists of two separate things. 1 is start of implementation of template literal, 2 is putting the self.next inside the match construct.

**Comment by jasonwilliams** [comment]
@croraf this would need some tests to show it working

**Comment by croraf** [comment]
I added 2 tests.

**Comment by jasonwilliams** [comment]
@croraf thanks, I’ll have a play with this

**Comment by croraf** [comment]
This will be split in 2 PRs and closed.

**Comment by Razican** [comment]
I think the template lexing has been implemented in #455, right? Can we close this?

**Comment by croraf** [comment]
I wanted to do a minor refactor of lexer that is present as part of this PR but otherwise the PR is obsolete.

**Comment by croraf** [comment]
From this only remains the small `match` construct refactor in main lexer loop. Instead of getting the next character before `match` I put it as a part of the `match`. Check boa/src/syntax/lexer/mod.rs in the changed files.

If you like it I will make a separate PR with it?

**Comment by Razican** [comment]
> If you like it I will make a separate PR with it?

All that will soon change with #432. I think it's best to invest on that by doing PRs to that branch :)

**Comment by croraf** [comment]
@Razican I thought so. I will close this then.

**Pull request closed without merging**
