### PR TITLE
 Add a way to add setters/getters in js_class! 

### PR DESCRIPTION
**Pull request by hansl**
And update documentation for more explanation around the macro.

### CODE REVIEW

**Comment by hansl** [comment]
Converting to draft as I've come up with a better interface for getter/setter. Basically:

```rust
prop name_of_prop as "nameOfProp" {
  fn getter(...) {}
  fn setter(...) {}
}
```

with getter and setter optional. That way we don't need 3 sections for properties and it's a bit simpler.

**Comment by hansl** [comment]
Okay this does use the new API now.

**Review by jedel1043 — APPROVED** [review]
Good work! Looks perfect to me.

**Comment by jedel1043** [comment]
Thought: the syntax is getting a bit too DSL-like, so I'll probably see if I can start working on that derive macro.

**Review by raskad — APPROVED** [review]

**Pull request merged**
