### PR TITLE
Fix wrong `neg` operation

### PR DESCRIPTION
**Pull request by CrazyboyQCD**
Negative `boolean` and `null` should return negative value

### CODE REVIEW

**Review by jedel1043 — COMMENTED** [review]
Good catch! Can you add a test for it? Apparently test262 didn't have a test for this.

**Comment by CrazyboyQCD** [comment]
> Good catch! Can you add a test for it? Apparently test262 didn't have a test for this.

Done.

**Review by jedel1043 — APPROVED** [review]
Thank you!

**Review by HalidOdat — APPROVED** [review]
Nice catch!

**Pull request merged**
