### PR TITLE
[Merged by Bors] - Implement `Object.prototype.__defineSetter__`

### PR DESCRIPTION
**Pull request by wusyong**
This Pull Request fixes part of https://github.com/boa-dev/boa/issues/2067.

It adds the legacy `Object.prototype.__defineSetter__` function.

### CODE REVIEW

**Review by jedel1043 — APPROVED** [review]
LGTM. Thank you for your contribution! :D

**Comment by jedel1043** [comment]
#### VM implementation
  | Test result | main count | PR count | difference |
  | :---------: | :----------: | :------: | :--------: |
  | Total | 90,499 | 90,499 | 0 |
  | Passed | 56,394 | 56,416 | **+22** |
  | Ignored | 23,580 | 23,580 | 0 |
  | Failed | 10,525 | 10,503 | **-22** |
  | Panics | 0 | 0 | 0 |
  | Conformance | 62.31% | 62.34% | **+0.02%** |
  
  <details><summary><b>Fixed tests (22):</b></summary>
  
  ```
  test/built-ins/Object/prototype/__defineSetter__/key-invalid.js [strict mode] (previously Failed)
  test/built-ins/Object/prototype/__defineSetter__/key-invalid.js (previously Failed)
  test/built-ins/Object/prototype/__defineSetter__/this-non-obj.js [strict mode] (previously Failed)
  test/built-ins/Object/prototype/__defineSetter__/this-non-obj.js (previously Failed)
  test/built-ins/Object/prototype/__defineSetter__/define-existing.js [strict mode] (previously Failed)
  test/built-ins/Object/prototype/__defineSetter__/define-existing.js (previously Failed)
  test/built-ins/Object/prototype/__defineSetter__/define-non-extensible.js [strict mode] (previously Failed)
  test/built-ins/Object/prototype/__defineSetter__/define-non-extensible.js (previously Failed)
  test/built-ins/Object/prototype/__defineSetter__/define-new.js [strict mode] (previously Failed)
  test/built-ins/Object/prototype/__defineSetter__/define-new.js (previously Failed)
  test/built-ins/Object/prototype/__defineSetter__/length.js [strict mode] (previously Failed)
  test/built-ins/Object/prototype/__defineSetter__/length.js (previously Failed)
  test/built-ins/Object/prototype/__defineSetter__/setter-non-callable.js [strict mode] (previously Failed)
  test/built-ins/Object/prototype/__defineSetter__/setter-non-callable.js (previously Failed)
  test/built-ins/Object/prototype/__defineSetter__/name.js [strict mode] (previously Failed)
  test/built-ins/Object/prototype/__defineSetter__/name.js (previously Failed)
  test/built-ins/Object/prototype/__defineSetter__/prop-desc.js [strict mode] (previously Failed)
  test/built-ins/Object/prototype/__defineSetter__/prop-desc.js (previously Failed)
  test/built-ins/Object/prototype/__defineSetter__/define-abrupt.js [strict mode] (previously Failed)
  test/built-ins/Object/prototype/__defineSetter__/define-abrupt.js (previously Failed)
  test/built-ins/Object/prototype/__defineSetter__/define-non-configurable.js [strict mode] (previously Failed)
  test/built-ins/Object/prototype/__defineSetter__/define-non-configurable.js (previously Failed)
  ```
  </details>

**Review by Razican — APPROVED** [review]
Thank you! Looks great :)

**Pull request closed without merging**
